// Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package testing

import (
	"fmt"
	"runtime"
)

var globalRegistry *Registry   // singleton, initialized on first use
var registrationErrors []error // singleton for errors encountered in AddTest calls

// GlobalRegistry returns a global registry containing tests
// registered by calls to AddTest.
func GlobalRegistry() *Registry {
	if globalRegistry == nil {
		globalRegistry = NewRegistry()
	}
	return globalRegistry
}

// RegistrationErrors returns errors generated by calls to AddTest.
func RegistrationErrors() []error {
	return registrationErrors
}

// AddTest adds test T to the global registry.
func AddTest(t *Test) {
	if err := GlobalRegistry().AddTest(t); err != nil {
		_, file, line, _ := runtime.Caller(1)
		if registrationErrors == nil {
			registrationErrors = make([]error, 0)
		}
		registrationErrors = append(registrationErrors, fmt.Errorf("%s:%d: %v", file, line, err))
	}
}

// SetGlobalRegistryForTesting temporarily sets reg as the global registry and clears registration errors.
// The caller must call the returned function later to restore the original registry and errors.
// This is intended to be used by unit tests that need to register tests in the global registry but don't
// want to affect subsequent unit tests.
func SetGlobalRegistryForTesting(reg *Registry) (restore func()) {
	origReg := globalRegistry
	origErrs := registrationErrors

	globalRegistry = reg
	registrationErrors = nil

	return func() {
		globalRegistry = origReg
		registrationErrors = origErrs
	}
}
