// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/design_id.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Uniquely identifies a Chromium OS hardware design project.
type DesignId struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DesignId) Reset()         { *m = DesignId{} }
func (m *DesignId) String() string { return proto.CompactTextString(m) }
func (*DesignId) ProtoMessage()    {}
func (*DesignId) Descriptor() ([]byte, []int) {
	return fileDescriptor_253968b0e079cd9e, []int{0}
}

func (m *DesignId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesignId.Unmarshal(m, b)
}
func (m *DesignId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesignId.Marshal(b, m, deterministic)
}
func (m *DesignId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesignId.Merge(m, src)
}
func (m *DesignId) XXX_Size() int {
	return xxx_messageInfo_DesignId.Size(m)
}
func (m *DesignId) XXX_DiscardUnknown() {
	xxx_messageInfo_DesignId.DiscardUnknown(m)
}

var xxx_messageInfo_DesignId proto.InternalMessageInfo

func (m *DesignId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DesignId)(nil), "chromiumos.config.api.DesignId")
}

func init() { proto.RegisterFile("api/design_id.proto", fileDescriptor_253968b0e079cd9e) }

var fileDescriptor_253968b0e079cd9e = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0xc8, 0xd4,
	0x4f, 0x49, 0x2d, 0xce, 0x4c, 0xcf, 0x8b, 0xcf, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x4d, 0xce, 0x28, 0xca, 0xcf, 0xcd, 0x2c, 0xcd, 0xcd, 0x2f, 0xd6, 0x4b, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x4b, 0x2c, 0xc8, 0x54, 0x52, 0xe0, 0xe2, 0x70, 0x01, 0xab, 0xf4, 0x4c, 0x11,
	0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82,
	0x70, 0x9c, 0xb4, 0xa2, 0x34, 0xd2, 0xf3, 0xf5, 0x60, 0xba, 0xf5, 0xf2, 0x8b, 0xd2, 0xf5, 0x11,
	0x46, 0xe9, 0x43, 0x8c, 0xd2, 0x4f, 0xcf, 0xd7, 0x4f, 0x2c, 0xc8, 0x4c, 0x62, 0x03, 0xdb, 0x65,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x81, 0x88, 0x1b, 0x82, 0x00, 0x00, 0x00,
}
