// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/partner.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines contributing partners participating in the design, execution,
// and support of chromiumos projects.
type Partner struct {
	// Globally unique partner identifier.
	Id *PartnerId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Descriptive name (for humans) of the partner.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Email alias used for coordinating project execution.
	EmailGroup           string   `protobuf:"bytes,3,opt,name=email_group,json=emailGroup,proto3" json:"email_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partner) Reset()         { *m = Partner{} }
func (m *Partner) String() string { return proto.CompactTextString(m) }
func (*Partner) ProtoMessage()    {}
func (*Partner) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfca1f801b1a75e7, []int{0}
}

func (m *Partner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partner.Unmarshal(m, b)
}
func (m *Partner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partner.Marshal(b, m, deterministic)
}
func (m *Partner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partner.Merge(m, src)
}
func (m *Partner) XXX_Size() int {
	return xxx_messageInfo_Partner.Size(m)
}
func (m *Partner) XXX_DiscardUnknown() {
	xxx_messageInfo_Partner.DiscardUnknown(m)
}

var xxx_messageInfo_Partner proto.InternalMessageInfo

func (m *Partner) GetId() *PartnerId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Partner) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Partner) GetEmailGroup() string {
	if m != nil {
		return m.EmailGroup
	}
	return ""
}

type PartnerList struct {
	Value                []*Partner `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PartnerList) Reset()         { *m = PartnerList{} }
func (m *PartnerList) String() string { return proto.CompactTextString(m) }
func (*PartnerList) ProtoMessage()    {}
func (*PartnerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfca1f801b1a75e7, []int{1}
}

func (m *PartnerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartnerList.Unmarshal(m, b)
}
func (m *PartnerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartnerList.Marshal(b, m, deterministic)
}
func (m *PartnerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartnerList.Merge(m, src)
}
func (m *PartnerList) XXX_Size() int {
	return xxx_messageInfo_PartnerList.Size(m)
}
func (m *PartnerList) XXX_DiscardUnknown() {
	xxx_messageInfo_PartnerList.DiscardUnknown(m)
}

var xxx_messageInfo_PartnerList proto.InternalMessageInfo

func (m *PartnerList) GetValue() []*Partner {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Partner)(nil), "chromiumos.config.api.Partner")
	proto.RegisterType((*PartnerList)(nil), "chromiumos.config.api.PartnerList")
}

func init() { proto.RegisterFile("api/partner.proto", fileDescriptor_cfca1f801b1a75e7) }

var fileDescriptor_cfca1f801b1a75e7 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x3d, 0x4b, 0x04, 0x31,
	0x10, 0x86, 0xc9, 0x9e, 0x1f, 0x38, 0xa9, 0x0c, 0x0a, 0xc1, 0x42, 0xc3, 0x55, 0xc1, 0x22, 0x91,
	0xd3, 0x5f, 0xa0, 0x85, 0x08, 0x16, 0xb2, 0xa5, 0xcd, 0x11, 0x2f, 0x31, 0x0e, 0x5c, 0x76, 0x42,
	0x6e, 0xd7, 0xdf, 0x2f, 0x26, 0x8b, 0x5a, 0xc8, 0x75, 0xc3, 0x33, 0xcf, 0xfb, 0x0e, 0x03, 0xa7,
	0x2e, 0xa3, 0xcd, 0xae, 0x8c, 0x43, 0x28, 0x26, 0x17, 0x1a, 0x49, 0x9c, 0x6f, 0x3e, 0x0a, 0x25,
	0x9c, 0x12, 0xed, 0xcc, 0x86, 0x86, 0x77, 0x8c, 0xc6, 0x65, 0xbc, 0x38, 0xfb, 0x63, 0xae, 0xd1,
	0x37, 0x79, 0x99, 0xe1, 0xf8, 0xa5, 0x31, 0x71, 0x03, 0x1d, 0x7a, 0xc9, 0x14, 0xd3, 0x7c, 0xa5,
	0xcc, 0xbf, 0x25, 0x66, 0x76, 0x9f, 0x7c, 0xdf, 0xa1, 0x17, 0x02, 0x0e, 0x06, 0x97, 0x82, 0xec,
	0x14, 0xd3, 0x27, 0x7d, 0x9d, 0xc5, 0x15, 0xf0, 0x90, 0x1c, 0x6e, 0xd7, 0xb1, 0xd0, 0x94, 0xe5,
	0xa2, 0xae, 0xa0, 0xa2, 0xc7, 0x6f, 0xb2, 0x7c, 0x00, 0x3e, 0xb7, 0x3c, 0xe3, 0x6e, 0x14, 0x77,
	0x70, 0xf8, 0xe9, 0xb6, 0x53, 0x90, 0x4c, 0x2d, 0x34, 0x5f, 0x5d, 0xee, 0x3f, 0xdc, 0x37, 0xf9,
	0xfe, 0xfa, 0x55, 0x47, 0xfa, 0x51, 0x0d, 0x95, 0x68, 0x7f, 0x73, 0xb6, 0xe5, 0x6c, 0x24, 0xeb,
	0x32, 0xbe, 0x1d, 0xd5, 0x4f, 0x6f, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x7d, 0xb5, 0x68,
	0x2b, 0x01, 0x00, 0x00,
}
