// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/metadata/v1/remote_test_driver.proto

package metadata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// All supported Remote Test Drivers, per go/cros-f20.
type RemoteTestDriver_ID int32

const (
	// Unspecified emote Test Driver. Must not be used.
	RemoteTestDriver_ID_UNSPECIFIED RemoteTestDriver_ID = 0
	// See http://go/tauto-tests
	RemoteTestDriver_TAUTO RemoteTestDriver_ID = 1
	// See http://go/tast
	RemoteTestDriver_TAST RemoteTestDriver_ID = 2
)

var RemoteTestDriver_ID_name = map[int32]string{
	0: "ID_UNSPECIFIED",
	1: "TAUTO",
	2: "TAST",
}

var RemoteTestDriver_ID_value = map[string]int32{
	"ID_UNSPECIFIED": 0,
	"TAUTO":          1,
	"TAST":           2,
}

func (x RemoteTestDriver_ID) String() string {
	return proto.EnumName(RemoteTestDriver_ID_name, int32(x))
}

func (RemoteTestDriver_ID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_99c28781f9cad910, []int{0, 0}
}

// go/cros-rtd-spec describes the Remote Test Driver bootstrapping flow inside
// the Remote Test Server. Remote Test Driver configures the bootstrapping flow
// for a test invocation.
type RemoteTestDriver struct {
	// id is required to construct globally unique identifiers for test metadata.
	Id RemoteTestDriver_ID `protobuf:"varint,1,opt,name=id,proto3,enum=test.metadata.v1.RemoteTestDriver_ID" json:"id,omitempty"`
	// A container image containing all the required dependencies and other build
	// artifacts required for test invocations.
	//
	// Test Lab Environments should fail with an error indicating that the request
	// was invalid if the image fails to be found for a test invocation.
	Image *BuildArtifact `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Command to invoke the Remote Test Driver inside `image`.
	//
	// Remote Test Servers must run `command` as
	//   $ ${command} -input_json ${input_json}
	// where ${intput_json} is an absolute file path.
	//
	// Remote Test Servers must populate `input_json` with a JSON encoded
	// test.invocation.Request message.
	Command              string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteTestDriver) Reset()         { *m = RemoteTestDriver{} }
func (m *RemoteTestDriver) String() string { return proto.CompactTextString(m) }
func (*RemoteTestDriver) ProtoMessage()    {}
func (*RemoteTestDriver) Descriptor() ([]byte, []int) {
	return fileDescriptor_99c28781f9cad910, []int{0}
}

func (m *RemoteTestDriver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteTestDriver.Unmarshal(m, b)
}
func (m *RemoteTestDriver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteTestDriver.Marshal(b, m, deterministic)
}
func (m *RemoteTestDriver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteTestDriver.Merge(m, src)
}
func (m *RemoteTestDriver) XXX_Size() int {
	return xxx_messageInfo_RemoteTestDriver.Size(m)
}
func (m *RemoteTestDriver) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteTestDriver.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteTestDriver proto.InternalMessageInfo

func (m *RemoteTestDriver) GetId() RemoteTestDriver_ID {
	if m != nil {
		return m.Id
	}
	return RemoteTestDriver_ID_UNSPECIFIED
}

func (m *RemoteTestDriver) GetImage() *BuildArtifact {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *RemoteTestDriver) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

// A Chrome OS build artifact required for test execution.
type BuildArtifact struct {
	// All build artifacts are assumed to be archived in some common directory
	// root. `relative_path` is the relative path inside the root archive
	// directory.
	//
	// Infrastructure Test Lab Environment: Chrome OS Continuous Integration
	// builders archive build artifacts to a path on Google Storage. The Test
	// Platform requests include a reference to the root archival path.
	// e.g.,
	// * The builder archives all build artifacts to
	//   gs://chromeos-image-archive/link-release/R64-0.0.0.0/
	// * Test Platform request includes this archival path.
	// * `relative_path` is set to tast/mighty.bin
	// * Then, the full path to the artifact is
	//   gs://chromeos-image-archive/link-release/R64-0.0.0.0/tast/mighty.bin
	//
	// Developer Test Lab Environment: For developer flow outside of the
	// infrastructure, it is assumed that the build artifacts are available at a
	// local path with the same directory layout as the Google Storage archival.
	// e.g.,
	// * Local build copies all artifacts to /tmp/cbuildbot/archive/
	// * Local tooling includes a reference to this path.
	// * `relative_path` is set to tauto/ssp.bin
	// * Then, the full path to the artifact is
	//   /tmp/cbuildbot/archive/tauto/ssp.bin
	RelativePath         string   `protobuf:"bytes,1,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildArtifact) Reset()         { *m = BuildArtifact{} }
func (m *BuildArtifact) String() string { return proto.CompactTextString(m) }
func (*BuildArtifact) ProtoMessage()    {}
func (*BuildArtifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_99c28781f9cad910, []int{1}
}

func (m *BuildArtifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildArtifact.Unmarshal(m, b)
}
func (m *BuildArtifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildArtifact.Marshal(b, m, deterministic)
}
func (m *BuildArtifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildArtifact.Merge(m, src)
}
func (m *BuildArtifact) XXX_Size() int {
	return xxx_messageInfo_BuildArtifact.Size(m)
}
func (m *BuildArtifact) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildArtifact.DiscardUnknown(m)
}

var xxx_messageInfo_BuildArtifact proto.InternalMessageInfo

func (m *BuildArtifact) GetRelativePath() string {
	if m != nil {
		return m.RelativePath
	}
	return ""
}

func init() {
	proto.RegisterEnum("test.metadata.v1.RemoteTestDriver_ID", RemoteTestDriver_ID_name, RemoteTestDriver_ID_value)
	proto.RegisterType((*RemoteTestDriver)(nil), "test.metadata.v1.RemoteTestDriver")
	proto.RegisterType((*BuildArtifact)(nil), "test.metadata.v1.BuildArtifact")
}

func init() {
	proto.RegisterFile("test/metadata/v1/remote_test_driver.proto", fileDescriptor_99c28781f9cad910)
}

var fileDescriptor_99c28781f9cad910 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xff, 0xe9, 0xdf, 0xa9, 0x8d, 0x6e, 0x94, 0x9c, 0x7a, 0xb3, 0x54, 0x84, 0x7a, 0x30,
	0x61, 0xd3, 0x21, 0x1e, 0x3b, 0x3b, 0xa1, 0x17, 0x1d, 0x5d, 0x77, 0xf1, 0x52, 0x62, 0x93, 0xb5,
	0x81, 0x65, 0x19, 0xe9, 0xbb, 0x7e, 0x47, 0xbf, 0x95, 0xac, 0xd2, 0xc3, 0xe6, 0xf1, 0xf9, 0xf1,
	0x7b, 0x78, 0x79, 0x1f, 0x7c, 0x0f, 0xb2, 0x01, 0xa6, 0x25, 0x70, 0xc1, 0x81, 0xb3, 0x76, 0xcc,
	0xac, 0xd4, 0x06, 0x64, 0x71, 0xe0, 0x85, 0xb0, 0xaa, 0x95, 0x96, 0xee, 0xac, 0x01, 0x43, 0xbc,
	0x03, 0xa2, 0xbd, 0x4a, 0xdb, 0x71, 0xf8, 0x8d, 0xb0, 0x97, 0x75, 0x7a, 0x2e, 0x1b, 0x48, 0x3a,
	0x99, 0x4c, 0xb1, 0xa3, 0x84, 0x8f, 0x02, 0x14, 0x8d, 0x26, 0x77, 0xf4, 0xb4, 0x43, 0x4f, 0x7d,
	0x9a, 0x26, 0x99, 0xa3, 0x04, 0x99, 0xe2, 0x81, 0xd2, 0xbc, 0x92, 0xbe, 0x13, 0xa0, 0xe8, 0x6a,
	0x72, 0xf3, 0xb7, 0x39, 0xdb, 0xab, 0x8d, 0x88, 0x2d, 0xa8, 0x35, 0x2f, 0x21, 0xfb, 0xb5, 0x89,
	0x8f, 0x2f, 0x4a, 0xa3, 0x35, 0xdf, 0x0a, 0xff, 0x7f, 0x80, 0x22, 0x37, 0xeb, 0x63, 0xf8, 0x80,
	0x9d, 0x34, 0x21, 0x04, 0x8f, 0xd2, 0xa4, 0x58, 0xbd, 0x2f, 0x17, 0xf3, 0xd7, 0xf4, 0x2d, 0x9d,
	0x27, 0xde, 0x3f, 0xe2, 0xe2, 0x41, 0x1e, 0xaf, 0xf2, 0x0f, 0x0f, 0x91, 0x4b, 0x7c, 0x96, 0xc7,
	0xcb, 0xdc, 0x73, 0xc2, 0x27, 0x3c, 0x3c, 0x3a, 0x40, 0x6e, 0xf1, 0xd0, 0xca, 0x0d, 0x07, 0xd5,
	0xca, 0x62, 0xc7, 0xa1, 0xee, 0x5e, 0x72, 0xb3, 0xeb, 0x1e, 0x2e, 0x38, 0xd4, 0xb3, 0x97, 0xcf,
	0xe7, 0xca, 0xd0, 0xb2, 0xb6, 0x46, 0xab, 0xbd, 0xa6, 0xc6, 0x56, 0xac, 0x0f, 0xa6, 0x61, 0x6a,
	0xbb, 0xb6, 0x9c, 0x75, 0xeb, 0xb1, 0xca, 0xb0, 0xa3, 0xa9, 0xbf, 0xce, 0x3b, 0xfe, 0xf8, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x78, 0x9e, 0x45, 0xd4, 0x82, 0x01, 0x00, 0x00,
}
