// Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package testing

import (
	"fmt"
	"runtime"
)

var globalRegistry *Registry   // singleton, initialized on first use
var registrationErrors []error // singleton for errors encountered in AddTest calls

// GlobalRegistry returns a global registry containing tests
// registered by calls to AddTest.
func GlobalRegistry() *Registry {
	if globalRegistry == nil {
		globalRegistry = NewRegistry()
	}
	return globalRegistry
}

// RegistrationErrors returns errors generated by calls to AddTest.
func RegistrationErrors() []error {
	return registrationErrors
}

// AddTest adds test T to the global registry.
func AddTest(t *Test) {
	if err := GlobalRegistry().AddTest(t); err != nil {
		_, file, line, _ := runtime.Caller(1)
		if registrationErrors == nil {
			registrationErrors = make([]error, 0)
		}
		registrationErrors = append(registrationErrors, fmt.Errorf("%s:%d: %v", file, line, err))
	}
}

// ClearForTesting clears all registered tests and registration errors.
// It should only be called from unit tests.
func ClearForTesting() {
	globalRegistry = nil
	registrationErrors = nil
}
