// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bundle.proto

package bundle

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pre_Method int32

const (
	Pre_PREPARE Pre_Method = 0
	Pre_CLEAN   Pre_Method = 1
	Pre_CLOSE   Pre_Method = 2
)

var Pre_Method_name = map[int32]string{
	0: "PREPARE",
	1: "CLEAN",
	2: "CLOSE",
}

var Pre_Method_value = map[string]int32{
	"PREPARE": 0,
	"CLEAN":   1,
	"CLOSE":   2,
}

func (x Pre_Method) String() string {
	return proto.EnumName(Pre_Method_name, int32(x))
}

func (Pre_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{6, 0}
}

type PrepareRequset struct {
	// args is json serialized args.
	Args                 string   `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareRequset) Reset()         { *m = PrepareRequset{} }
func (m *PrepareRequset) String() string { return proto.CompactTextString(m) }
func (*PrepareRequset) ProtoMessage()    {}
func (*PrepareRequset) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{0}
}

func (m *PrepareRequset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareRequset.Unmarshal(m, b)
}
func (m *PrepareRequset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareRequset.Marshal(b, m, deterministic)
}
func (m *PrepareRequset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareRequset.Merge(m, src)
}
func (m *PrepareRequset) XXX_Size() int {
	return xxx_messageInfo_PrepareRequset.Size(m)
}
func (m *PrepareRequset) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareRequset.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareRequset proto.InternalMessageInfo

func (m *PrepareRequset) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type PrepareResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareResponse) Reset()         { *m = PrepareResponse{} }
func (m *PrepareResponse) String() string { return proto.CompactTextString(m) }
func (*PrepareResponse) ProtoMessage()    {}
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{1}
}

func (m *PrepareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareResponse.Unmarshal(m, b)
}
func (m *PrepareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareResponse.Marshal(b, m, deterministic)
}
func (m *PrepareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareResponse.Merge(m, src)
}
func (m *PrepareResponse) XXX_Size() int {
	return xxx_messageInfo_PrepareResponse.Size(m)
}
func (m *PrepareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareResponse proto.InternalMessageInfo

type ListRequest struct {
	// args is json serialized Args.
	Args string `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	// expr is attribute expressions.
	Expr                 []string `protobuf:"bytes,2,rep,name=expr,proto3" json:"expr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *ListRequest) GetExpr() []string {
	if m != nil {
		return m.Expr
	}
	return nil
}

type ListResponse struct {
	Test                 []*TestInfo `protobuf:"bytes,1,rep,name=test,proto3" json:"test,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{3}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetTest() []*TestInfo {
	if m != nil {
		return m.Test
	}
	return nil
}

type RunRequest struct {
	// args is json serialized Args.
	Args string `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	// test is the tests to run.
	// Preconditioins' method should be CLEAR or CLOSE to indicate
	// the method to run after the main test finishes.
	Test *TestInfo `protobuf:"bytes,2,opt,name=test,proto3" json:"test,omitempty"`
	// pre is the precondition to run.
	// This field is used for running remote precondition
	// before running a local test having the precondition.
	// If if pre.method is PREPARE, run prepare phase.
	// Otherwise run clean up phase.
	Pre                  *Pre     `protobuf:"bytes,3,opt,name=pre,proto3" json:"pre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{4}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *RunRequest) GetTest() *TestInfo {
	if m != nil {
		return m.Test
	}
	return nil
}

func (m *RunRequest) GetPre() *Pre {
	if m != nil {
		return m.Pre
	}
	return nil
}

type RunResponse struct {
	// control is json serialized message of control.Run*
	Control              string   `protobuf:"bytes,1,opt,name=control,proto3" json:"control,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{5}
}

func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (m *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(m, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetControl() string {
	if m != nil {
		return m.Control
	}
	return ""
}

type Pre struct {
	// name is the name of this precondition.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// parent is the parent precondition if any.
	Parent *Pre `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	// external_parent is the name of the parent resides in a
	// different bundle.
	ExternalParent       string     `protobuf:"bytes,3,opt,name=external_parent,json=externalParent,proto3" json:"external_parent,omitempty"`
	Method               Pre_Method `protobuf:"varint,4,opt,name=method,proto3,enum=tast.core.Pre_Method" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Pre) Reset()         { *m = Pre{} }
func (m *Pre) String() string { return proto.CompactTextString(m) }
func (*Pre) ProtoMessage()    {}
func (*Pre) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{6}
}

func (m *Pre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pre.Unmarshal(m, b)
}
func (m *Pre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pre.Marshal(b, m, deterministic)
}
func (m *Pre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pre.Merge(m, src)
}
func (m *Pre) XXX_Size() int {
	return xxx_messageInfo_Pre.Size(m)
}
func (m *Pre) XXX_DiscardUnknown() {
	xxx_messageInfo_Pre.DiscardUnknown(m)
}

var xxx_messageInfo_Pre proto.InternalMessageInfo

func (m *Pre) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pre) GetParent() *Pre {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Pre) GetExternalParent() string {
	if m != nil {
		return m.ExternalParent
	}
	return ""
}

func (m *Pre) GetMethod() Pre_Method {
	if m != nil {
		return m.Method
	}
	return Pre_PREPARE
}

type TestInfo struct {
	// name is the test name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// precondition is the precondition the test declares.
	Precondition *Pre `protobuf:"bytes,2,opt,name=precondition,proto3" json:"precondition,omitempty"`
	// skip_reason is non-empty if the test should be skipped.
	SkipReason           string   `protobuf:"bytes,3,opt,name=skip_reason,json=skipReason,proto3" json:"skip_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestInfo) Reset()         { *m = TestInfo{} }
func (m *TestInfo) String() string { return proto.CompactTextString(m) }
func (*TestInfo) ProtoMessage()    {}
func (*TestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf01a1817f9fc5c2, []int{7}
}

func (m *TestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInfo.Unmarshal(m, b)
}
func (m *TestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInfo.Marshal(b, m, deterministic)
}
func (m *TestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInfo.Merge(m, src)
}
func (m *TestInfo) XXX_Size() int {
	return xxx_messageInfo_TestInfo.Size(m)
}
func (m *TestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TestInfo proto.InternalMessageInfo

func (m *TestInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestInfo) GetPrecondition() *Pre {
	if m != nil {
		return m.Precondition
	}
	return nil
}

func (m *TestInfo) GetSkipReason() string {
	if m != nil {
		return m.SkipReason
	}
	return ""
}

func init() {
	proto.RegisterEnum("tast.core.Pre_Method", Pre_Method_name, Pre_Method_value)
	proto.RegisterType((*PrepareRequset)(nil), "tast.core.PrepareRequset")
	proto.RegisterType((*PrepareResponse)(nil), "tast.core.PrepareResponse")
	proto.RegisterType((*ListRequest)(nil), "tast.core.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "tast.core.ListResponse")
	proto.RegisterType((*RunRequest)(nil), "tast.core.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "tast.core.RunResponse")
	proto.RegisterType((*Pre)(nil), "tast.core.Pre")
	proto.RegisterType((*TestInfo)(nil), "tast.core.TestInfo")
}

func init() { proto.RegisterFile("bundle.proto", fileDescriptor_cf01a1817f9fc5c2) }

var fileDescriptor_cf01a1817f9fc5c2 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x9d, 0x9b, 0xd2, 0xd1, 0x9b, 0x92, 0x15, 0x23, 0x4a, 0xb4, 0x17, 0x22, 0x0b, 0xd1, 0x4a,
	0x88, 0x0c, 0x05, 0x21, 0xe0, 0x71, 0x43, 0x79, 0x40, 0x1a, 0x10, 0x79, 0x3c, 0xf1, 0x32, 0x65,
	0xe9, 0x85, 0x45, 0x6b, 0xec, 0x60, 0x3b, 0x68, 0x3f, 0x80, 0xdf, 0xc6, 0xef, 0x42, 0x76, 0x92,
	0x91, 0x8d, 0xad, 0x6f, 0xd7, 0xe7, 0x9e, 0x7b, 0xee, 0x87, 0x8e, 0x61, 0x76, 0xd6, 0x88, 0xf5,
	0x06, 0xe3, 0x5a, 0x49, 0x23, 0xe9, 0xd4, 0xe4, 0xda, 0xc4, 0x85, 0x54, 0xc8, 0x9e, 0x41, 0x90,
	0x29, 0xac, 0x73, 0x85, 0x1c, 0x7f, 0x36, 0x1a, 0x0d, 0xa5, 0x30, 0xce, 0xd5, 0x0f, 0x1d, 0x92,
	0x88, 0xac, 0xa6, 0xdc, 0xc5, 0xec, 0x21, 0xec, 0x5d, 0xb1, 0x74, 0x2d, 0x85, 0x46, 0xf6, 0x06,
	0xfc, 0xe3, 0x52, 0x1b, 0x5b, 0x85, 0xfa, 0xd6, 0x2a, 0x8b, 0xe1, 0x65, 0xad, 0xc2, 0x51, 0xe4,
	0x59, 0xcc, 0xc6, 0xec, 0x2d, 0xcc, 0xda, 0xb2, 0x56, 0x86, 0x2e, 0x61, 0x6c, 0x50, 0x9b, 0x90,
	0x44, 0xde, 0xca, 0x4f, 0x1e, 0xc5, 0x57, 0x93, 0xc5, 0x5f, 0x51, 0x9b, 0x8f, 0xe2, 0xbb, 0xe4,
	0x8e, 0xc0, 0x2e, 0x00, 0x78, 0x23, 0xb6, 0xb5, 0xeb, 0xa5, 0x46, 0x11, 0xd9, 0x2a, 0x45, 0x23,
	0xf0, 0x6a, 0x85, 0xa1, 0xe7, 0x78, 0xc1, 0x80, 0x97, 0x29, 0xe4, 0x36, 0xc5, 0x96, 0xe0, 0xbb,
	0x66, 0xdd, 0x90, 0x21, 0xec, 0x16, 0x52, 0x18, 0x25, 0x37, 0x5d, 0xc3, 0xfe, 0xc9, 0xfe, 0x10,
	0xf0, 0x32, 0x85, 0x76, 0x1e, 0x91, 0x57, 0xd8, 0xcf, 0x63, 0x63, 0xfa, 0x1c, 0x26, 0xf6, 0x62,
	0xa2, 0x9f, 0xe8, 0x66, 0xa7, 0x2e, 0x4b, 0x97, 0xb0, 0x87, 0x97, 0x06, 0x95, 0xc8, 0x37, 0xa7,
	0x5d, 0x81, 0xe7, 0x64, 0x82, 0x1e, 0xce, 0x5a, 0xe2, 0x4b, 0x98, 0x54, 0x68, 0xce, 0xe5, 0x3a,
	0x1c, 0x47, 0x64, 0x15, 0x24, 0x8f, 0xaf, 0x0b, 0xc6, 0x9f, 0x5c, 0x92, 0x77, 0x24, 0xf6, 0x02,
	0x26, 0x2d, 0x42, 0x7d, 0xd8, 0xcd, 0x78, 0x9a, 0x1d, 0xf2, 0x74, 0xbe, 0x43, 0xa7, 0x70, 0xef,
	0xc3, 0x71, 0x7a, 0xf8, 0x79, 0x4e, 0xda, 0xf0, 0xcb, 0x49, 0x3a, 0x1f, 0x31, 0x0d, 0xf7, 0xfb,
	0x2b, 0xdd, 0xba, 0x4c, 0x02, 0xb3, 0x5a, 0x61, 0x21, 0xc5, 0xba, 0x34, 0xa5, 0x14, 0x77, 0xac,
	0x74, 0x8d, 0x43, 0x9f, 0x82, 0xaf, 0x2f, 0xca, 0xfa, 0x54, 0x61, 0xae, 0xa5, 0xe8, 0x96, 0x02,
	0x0b, 0x71, 0x87, 0x24, 0xbf, 0x09, 0x3c, 0x38, 0x72, 0xc6, 0x3c, 0x41, 0xf5, 0xab, 0x2c, 0x90,
	0xbe, 0x87, 0xb1, 0xb5, 0x07, 0x5d, 0x0c, 0x84, 0x07, 0x36, 0xdb, 0x7f, 0xf2, 0x1f, 0xde, 0xd9,
	0x71, 0x87, 0xbe, 0x03, 0x8f, 0x37, 0x82, 0x0e, 0x8f, 0xf2, 0xcf, 0x30, 0xfb, 0x8b, 0x9b, 0x70,
	0x5f, 0xf7, 0x8a, 0x1c, 0x85, 0xdf, 0x16, 0xc5, 0xb9, 0x92, 0x55, 0xd9, 0x54, 0x52, 0x1f, 0x58,
	0xde, 0x41, 0xfb, 0x5d, 0xce, 0x26, 0xee, 0xbf, 0xbc, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf9,
	0x9e, 0x90, 0xe6, 0x3f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BundleServiceClient is the client API for BundleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BundleServiceClient interface {
	// rpc Prepare(PrepareRequset) returns (PrepareResponse) {}
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (BundleService_RunClient, error)
}

type bundleServiceClient struct {
	cc *grpc.ClientConn
}

func NewBundleServiceClient(cc *grpc.ClientConn) BundleServiceClient {
	return &bundleServiceClient{cc}
}

func (c *bundleServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/tast.core.BundleService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bundleServiceClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (BundleService_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BundleService_serviceDesc.Streams[0], "/tast.core.BundleService/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &bundleServiceRunClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BundleService_RunClient interface {
	Recv() (*RunResponse, error)
	grpc.ClientStream
}

type bundleServiceRunClient struct {
	grpc.ClientStream
}

func (x *bundleServiceRunClient) Recv() (*RunResponse, error) {
	m := new(RunResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BundleServiceServer is the server API for BundleService service.
type BundleServiceServer interface {
	// rpc Prepare(PrepareRequset) returns (PrepareResponse) {}
	List(context.Context, *ListRequest) (*ListResponse, error)
	Run(*RunRequest, BundleService_RunServer) error
}

// UnimplementedBundleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBundleServiceServer struct {
}

func (*UnimplementedBundleServiceServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedBundleServiceServer) Run(req *RunRequest, srv BundleService_RunServer) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterBundleServiceServer(s *grpc.Server, srv BundleServiceServer) {
	s.RegisterService(&_BundleService_serviceDesc, srv)
}

func _BundleService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BundleServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.core.BundleService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BundleServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BundleService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BundleServiceServer).Run(m, &bundleServiceRunServer{stream})
}

type BundleService_RunServer interface {
	Send(*RunResponse) error
	grpc.ServerStream
}

type bundleServiceRunServer struct {
	grpc.ServerStream
}

func (x *bundleServiceRunServer) Send(m *RunResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BundleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.core.BundleService",
	HandlerType: (*BundleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BundleService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _BundleService_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bundle.proto",
}
