// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bundle_messages.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitBundleServerRequest struct {
	Vars                 map[string]string `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitBundleServerRequest) Reset()         { *m = InitBundleServerRequest{} }
func (m *InitBundleServerRequest) String() string { return proto.CompactTextString(m) }
func (*InitBundleServerRequest) ProtoMessage()    {}
func (*InitBundleServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_947083ba6d1b95d0, []int{0}
}

func (m *InitBundleServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBundleServerRequest.Unmarshal(m, b)
}
func (m *InitBundleServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBundleServerRequest.Marshal(b, m, deterministic)
}
func (m *InitBundleServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBundleServerRequest.Merge(m, src)
}
func (m *InitBundleServerRequest) XXX_Size() int {
	return xxx_messageInfo_InitBundleServerRequest.Size(m)
}
func (m *InitBundleServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBundleServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitBundleServerRequest proto.InternalMessageInfo

func (m *InitBundleServerRequest) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

type InitBundleServerResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitBundleServerResponse) Reset()         { *m = InitBundleServerResponse{} }
func (m *InitBundleServerResponse) String() string { return proto.CompactTextString(m) }
func (*InitBundleServerResponse) ProtoMessage()    {}
func (*InitBundleServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_947083ba6d1b95d0, []int{1}
}

func (m *InitBundleServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitBundleServerResponse.Unmarshal(m, b)
}
func (m *InitBundleServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitBundleServerResponse.Marshal(b, m, deterministic)
}
func (m *InitBundleServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitBundleServerResponse.Merge(m, src)
}
func (m *InitBundleServerResponse) XXX_Size() int {
	return xxx_messageInfo_InitBundleServerResponse.Size(m)
}
func (m *InitBundleServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitBundleServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitBundleServerResponse proto.InternalMessageInfo

func (m *InitBundleServerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *InitBundleServerResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*InitBundleServerRequest)(nil), "tast.core.InitBundleServerRequest")
	proto.RegisterMapType((map[string]string)(nil), "tast.core.InitBundleServerRequest.VarsEntry")
	proto.RegisterType((*InitBundleServerResponse)(nil), "tast.core.InitBundleServerResponse")
}

func init() { proto.RegisterFile("bundle_messages.proto", fileDescriptor_947083ba6d1b95d0) }

var fileDescriptor_947083ba6d1b95d0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2a, 0xcd, 0x4b,
	0xc9, 0x49, 0x8d, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x2c, 0x49, 0x2c, 0x2e, 0xd1, 0x4b, 0xce, 0x2f, 0x4a, 0x55, 0x9a, 0xc2, 0xc8,
	0x25, 0xee, 0x99, 0x97, 0x59, 0xe2, 0x04, 0x56, 0x18, 0x9c, 0x5a, 0x54, 0x96, 0x5a, 0x14, 0x94,
	0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xe4, 0xc0, 0xc5, 0x52, 0x96, 0x58, 0x54, 0x2c, 0xc1, 0xa8,
	0xc0, 0xac, 0xc1, 0x6d, 0xa4, 0xa3, 0x07, 0xd7, 0xa5, 0x87, 0x43, 0x87, 0x5e, 0x58, 0x62, 0x51,
	0xb1, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x58, 0xa7, 0x94, 0x39, 0x17, 0x27, 0x5c, 0x48, 0x48,
	0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x14, 0x12,
	0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x56, 0x4c, 0x16,
	0x8c, 0x4a, 0x91, 0x5c, 0x12, 0x98, 0x76, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x49, 0x70,
	0xb1, 0x17, 0x97, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x83, 0xcd, 0xe2, 0x08, 0x82, 0x71, 0x85, 0x94,
	0xb9, 0x78, 0x53, 0x8b, 0x8a, 0xf2, 0x8b, 0x60, 0xfe, 0x85, 0x9a, 0xcb, 0x03, 0x16, 0xf4, 0x85,
	0x88, 0x39, 0x89, 0x46, 0x09, 0x27, 0x67, 0x14, 0xe5, 0xe7, 0x66, 0x96, 0xe6, 0xe6, 0x17, 0xeb,
	0x83, 0xfc, 0xa4, 0x5f, 0x54, 0x90, 0x9c, 0xc4, 0x06, 0x0e, 0x1a, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xde, 0x1f, 0xfc, 0x97, 0x33, 0x01, 0x00, 0x00,
}
