// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/software/build_target.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Defines a portage overlay target and corresponding parameters that will be
// used during the build and apply to all devices supported by a given build.
type BuildTarget struct {
	Id *BuildTargetId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Portage overlay name
	OverlayName          string                          `protobuf:"bytes,2,opt,name=overlay_name,json=overlayName,proto3" json:"overlay_name,omitempty"`
	Arc                  *BuildTarget_ArcBuildProperties `protobuf:"bytes,3,opt,name=arc,proto3" json:"arc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *BuildTarget) Reset()         { *m = BuildTarget{} }
func (m *BuildTarget) String() string { return proto.CompactTextString(m) }
func (*BuildTarget) ProtoMessage()    {}
func (*BuildTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf39d5a80abe3b5a, []int{0}
}

func (m *BuildTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget.Unmarshal(m, b)
}
func (m *BuildTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget.Marshal(b, m, deterministic)
}
func (m *BuildTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget.Merge(m, src)
}
func (m *BuildTarget) XXX_Size() int {
	return xxx_messageInfo_BuildTarget.Size(m)
}
func (m *BuildTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget proto.InternalMessageInfo

func (m *BuildTarget) GetId() *BuildTargetId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *BuildTarget) GetOverlayName() string {
	if m != nil {
		return m.OverlayName
	}
	return ""
}

func (m *BuildTarget) GetArc() *BuildTarget_ArcBuildProperties {
	if m != nil {
		return m.Arc
	}
	return nil
}

// Build-specific ARC properties that are merged with device specific
// properties at runtime when ARC is initialized.
type BuildTarget_ArcBuildProperties struct {
	// Device name to report in ‘ro.product.device’.
	// This is often ‘{product}_cheets’ but it can be something else if
	// desired.
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// The first Android API level that this build shipped with.
	FirstApiLevel        string   `protobuf:"bytes,2,opt,name=first_api_level,json=firstApiLevel,proto3" json:"first_api_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildTarget_ArcBuildProperties) Reset()         { *m = BuildTarget_ArcBuildProperties{} }
func (m *BuildTarget_ArcBuildProperties) String() string { return proto.CompactTextString(m) }
func (*BuildTarget_ArcBuildProperties) ProtoMessage()    {}
func (*BuildTarget_ArcBuildProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf39d5a80abe3b5a, []int{0, 0}
}

func (m *BuildTarget_ArcBuildProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget_ArcBuildProperties.Unmarshal(m, b)
}
func (m *BuildTarget_ArcBuildProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget_ArcBuildProperties.Marshal(b, m, deterministic)
}
func (m *BuildTarget_ArcBuildProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget_ArcBuildProperties.Merge(m, src)
}
func (m *BuildTarget_ArcBuildProperties) XXX_Size() int {
	return xxx_messageInfo_BuildTarget_ArcBuildProperties.Size(m)
}
func (m *BuildTarget_ArcBuildProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget_ArcBuildProperties.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget_ArcBuildProperties proto.InternalMessageInfo

func (m *BuildTarget_ArcBuildProperties) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *BuildTarget_ArcBuildProperties) GetFirstApiLevel() string {
	if m != nil {
		return m.FirstApiLevel
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildTarget)(nil), "chromiumos.config.api.software.BuildTarget")
	proto.RegisterType((*BuildTarget_ArcBuildProperties)(nil), "chromiumos.config.api.software.BuildTarget.ArcBuildProperties")
}

func init() { proto.RegisterFile("api/software/build_target.proto", fileDescriptor_bf39d5a80abe3b5a) }

var fileDescriptor_bf39d5a80abe3b5a = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x69, 0x0a, 0x85, 0x6e, 0xfe, 0x7f, 0x84, 0x3d, 0x48, 0xe8, 0x41, 0x6b, 0x0f, 0xd2,
	0x8b, 0xbb, 0x68, 0xcf, 0x0a, 0xed, 0x4d, 0x10, 0x29, 0xa1, 0x27, 0x2f, 0x61, 0x9b, 0x9d, 0xc4,
	0x81, 0xa4, 0xb3, 0x4c, 0xb6, 0x11, 0x3f, 0x89, 0x5f, 0x57, 0xb2, 0x8d, 0x5a, 0x10, 0x05, 0x8f,
	0xf3, 0x1e, 0xf3, 0xde, 0x6f, 0x46, 0x9c, 0x1b, 0x87, 0xba, 0xa1, 0xc2, 0xbf, 0x18, 0x06, 0xbd,
	0xdd, 0x63, 0x65, 0x33, 0x6f, 0xb8, 0x04, 0xaf, 0x1c, 0x93, 0x27, 0x79, 0x96, 0x3f, 0x33, 0xd5,
	0xb8, 0xaf, 0xa9, 0x51, 0x39, 0xed, 0x0a, 0x2c, 0x95, 0x71, 0xa8, 0x3e, 0x56, 0x26, 0xb3, 0x1f,
	0x03, 0x32, 0xb4, 0x87, 0x8c, 0xd9, 0x5b, 0x24, 0xe2, 0x55, 0xe7, 0x6c, 0x82, 0x21, 0x6f, 0x45,
	0x84, 0x36, 0x19, 0x4c, 0x07, 0xf3, 0xf8, 0xe6, 0x4a, 0xfd, 0x5e, 0xa0, 0x8e, 0x16, 0xef, 0x6d,
	0x1a, 0xa1, 0x95, 0x17, 0xe2, 0x1f, 0xb5, 0xc0, 0x95, 0x79, 0xcd, 0x76, 0xa6, 0x86, 0x24, 0x9a,
	0x0e, 0xe6, 0xe3, 0x34, 0xee, 0xb5, 0x47, 0x53, 0x83, 0x5c, 0x8b, 0xa1, 0xe1, 0x3c, 0x19, 0x86,
	0x8a, 0xbb, 0x3f, 0x54, 0xa8, 0x25, 0xe7, 0x61, 0x5c, 0x33, 0x39, 0x60, 0x8f, 0xd0, 0xa4, 0x5d,
	0xd4, 0x64, 0x23, 0xe4, 0x77, 0x4b, 0x9e, 0x8a, 0x91, 0x85, 0x16, 0x73, 0x08, 0xd7, 0x8c, 0xd3,
	0x7e, 0x92, 0x97, 0xe2, 0xa4, 0x40, 0x6e, 0x7c, 0x66, 0x1c, 0x66, 0x15, 0xb4, 0x50, 0xf5, 0x94,
	0xff, 0x83, 0xbc, 0x74, 0xf8, 0xd0, 0x89, 0xab, 0xc5, 0xd3, 0x75, 0x49, 0x9f, 0x78, 0x8a, 0xb8,
	0xd4, 0x5f, 0xac, 0xfa, 0xc0, 0xaa, 0x4b, 0xd2, 0xc7, 0x4f, 0xde, 0x8e, 0xc2, 0x57, 0x17, 0xef,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x11, 0x2d, 0xc5, 0x39, 0xbc, 0x01, 0x00, 0x00,
}
