// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/software/build_target_id.proto

package software

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An id that other messages can use as a foreign key to specify a
// BuildTarget. Id messages are equal iff their binary serialization is
// equal.
type BuildTargetId struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildTargetId) Reset()         { *m = BuildTargetId{} }
func (m *BuildTargetId) String() string { return proto.CompactTextString(m) }
func (*BuildTargetId) ProtoMessage()    {}
func (*BuildTargetId) Descriptor() ([]byte, []int) {
	return fileDescriptor_79b372457295fbad, []int{0}
}

func (m *BuildTargetId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTargetId.Unmarshal(m, b)
}
func (m *BuildTargetId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTargetId.Marshal(b, m, deterministic)
}
func (m *BuildTargetId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTargetId.Merge(m, src)
}
func (m *BuildTargetId) XXX_Size() int {
	return xxx_messageInfo_BuildTargetId.Size(m)
}
func (m *BuildTargetId) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTargetId.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTargetId proto.InternalMessageInfo

func (m *BuildTargetId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildTargetId)(nil), "chromiumos.config.api.software.BuildTargetId")
}

func init() { proto.RegisterFile("api/software/build_target_id.proto", fileDescriptor_79b372457295fbad) }

var fileDescriptor_79b372457295fbad = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0x2c, 0xc8, 0xd4,
	0x2f, 0xce, 0x4f, 0x2b, 0x29, 0x4f, 0x2c, 0x4a, 0xd5, 0x4f, 0x2a, 0xcd, 0xcc, 0x49, 0x89, 0x2f,
	0x49, 0x2c, 0x4a, 0x4f, 0x2d, 0x89, 0xcf, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92,
	0x4b, 0xce, 0x28, 0xca, 0xcf, 0xcd, 0x2c, 0xcd, 0xcd, 0x2f, 0xd6, 0x4b, 0xce, 0xcf, 0x4b, 0xcb,
	0x4c, 0xd7, 0x4b, 0x2c, 0xc8, 0xd4, 0x83, 0xe9, 0x52, 0x52, 0xe5, 0xe2, 0x75, 0x02, 0x69, 0x0c,
	0x01, 0xeb, 0xf3, 0x4c, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x9c, 0x8c, 0xa3, 0x0c, 0xd3, 0xf3, 0xf5, 0x60, 0x66, 0xe9,
	0xe5, 0x17, 0xa5, 0xeb, 0x23, 0x0c, 0xd6, 0x87, 0x18, 0xac, 0x9f, 0x9e, 0xaf, 0x8f, 0xec, 0xa2,
	0x24, 0x36, 0xb0, 0x13, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xe1, 0xdd, 0x90, 0xa8,
	0x00, 0x00, 0x00,
}
