// Copyright 2021 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package symbolize

import (
	"bytes"
	"strings"
	"testing"

	"chromiumos/tast/cmd/tast/internal/logging"
)

func TestSymbolizeCrash(t *testing.T) {
	msg := "minidump does not contain release info, please supply --builderpath or --buildroot"
	tests := []struct {
		desc         string
		minidumpPath string
		buildRoot    string
		builderPath  string
		wantErr      *string
	}{
		{
			// Dumps generated by breakpad do not require extra parameters.
			desc:         "lsb-release",
			minidumpPath: "breakpad/testdata/abort.20180103.145440.12345.20827.dmp",
		},
		{
			// Show an error, when processing Crashpad dump without additional parameters.
			desc:         "no_lsb-release",
			minidumpPath: "breakpad/testdata/chrome.20210406.155226.62533.9042.dmp",
			wantErr:      &msg,
		},
	}
	for _, tt := range tests {
		t.Run(tt.desc, func(t *testing.T) {
			loggingBuf := bytes.Buffer{}
			cfg := Config{
				Logger:      logging.NewSimple(&loggingBuf /* datetime = */, false /* verbose = */, true),
				SymbolDir:   "/tmp/breakpad_symbols_test",
				BuildRoot:   tt.buildRoot,
				BuilderPath: tt.builderPath,
			}
			outputBuf := bytes.Buffer{}
			err := SymbolizeCrash(tt.minidumpPath, &outputBuf, cfg)
			if tt.wantErr == nil && err != nil {
				t.Errorf("got error: %q", err)
			} else if tt.wantErr != nil && err == nil {
				t.Error("expected error, but got none")
			} else if tt.wantErr != nil && !strings.Contains(err.Error(), *tt.wantErr) {
				t.Errorf("got unexpected error: %q", err)
			}
		})
	}
}
