// Code generated by protoc-gen-go. DO NOT EDIT.
// source: local_runner.proto

package runner

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	device "go.chromium.org/chromiumos/infra/proto/go/device"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DUTInfoRequest struct {
	ExtraUseFlags        []string `protobuf:"bytes,1,rep,name=extra_use_flags,json=extraUseFlags,proto3" json:"extra_use_flags,omitempty"`
	RequestDeviceConfig  bool     `protobuf:"varint,2,opt,name=request_device_config,json=requestDeviceConfig,proto3" json:"request_device_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DUTInfoRequest) Reset()         { *m = DUTInfoRequest{} }
func (m *DUTInfoRequest) String() string { return proto.CompactTextString(m) }
func (*DUTInfoRequest) ProtoMessage()    {}
func (*DUTInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810bb274fc749e19, []int{0}
}

func (m *DUTInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DUTInfoRequest.Unmarshal(m, b)
}
func (m *DUTInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DUTInfoRequest.Marshal(b, m, deterministic)
}
func (m *DUTInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DUTInfoRequest.Merge(m, src)
}
func (m *DUTInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DUTInfoRequest.Size(m)
}
func (m *DUTInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DUTInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DUTInfoRequest proto.InternalMessageInfo

func (m *DUTInfoRequest) GetExtraUseFlags() []string {
	if m != nil {
		return m.ExtraUseFlags
	}
	return nil
}

func (m *DUTInfoRequest) GetRequestDeviceConfig() bool {
	if m != nil {
		return m.RequestDeviceConfig
	}
	return false
}

type DUTInfoResponse struct {
	SoftwareFeatures     *SoftwareFeatures `protobuf:"bytes,1,opt,name=software_features,json=softwareFeatures,proto3" json:"software_features,omitempty"`
	DeviceConfig         *device.Config    `protobuf:"bytes,2,opt,name=device_config,json=deviceConfig,proto3" json:"device_config,omitempty"`
	Warnings             []string          `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DUTInfoResponse) Reset()         { *m = DUTInfoResponse{} }
func (m *DUTInfoResponse) String() string { return proto.CompactTextString(m) }
func (*DUTInfoResponse) ProtoMessage()    {}
func (*DUTInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_810bb274fc749e19, []int{1}
}

func (m *DUTInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DUTInfoResponse.Unmarshal(m, b)
}
func (m *DUTInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DUTInfoResponse.Marshal(b, m, deterministic)
}
func (m *DUTInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DUTInfoResponse.Merge(m, src)
}
func (m *DUTInfoResponse) XXX_Size() int {
	return xxx_messageInfo_DUTInfoResponse.Size(m)
}
func (m *DUTInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DUTInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DUTInfoResponse proto.InternalMessageInfo

func (m *DUTInfoResponse) GetSoftwareFeatures() *SoftwareFeatures {
	if m != nil {
		return m.SoftwareFeatures
	}
	return nil
}

func (m *DUTInfoResponse) GetDeviceConfig() *device.Config {
	if m != nil {
		return m.DeviceConfig
	}
	return nil
}

func (m *DUTInfoResponse) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type SoftwareFeatures struct {
	Available            []string `protobuf:"bytes,1,rep,name=available,proto3" json:"available,omitempty"`
	Unavailable          []string `protobuf:"bytes,2,rep,name=unavailable,proto3" json:"unavailable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoftwareFeatures) Reset()         { *m = SoftwareFeatures{} }
func (m *SoftwareFeatures) String() string { return proto.CompactTextString(m) }
func (*SoftwareFeatures) ProtoMessage()    {}
func (*SoftwareFeatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_810bb274fc749e19, []int{2}
}

func (m *SoftwareFeatures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoftwareFeatures.Unmarshal(m, b)
}
func (m *SoftwareFeatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoftwareFeatures.Marshal(b, m, deterministic)
}
func (m *SoftwareFeatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoftwareFeatures.Merge(m, src)
}
func (m *SoftwareFeatures) XXX_Size() int {
	return xxx_messageInfo_SoftwareFeatures.Size(m)
}
func (m *SoftwareFeatures) XXX_DiscardUnknown() {
	xxx_messageInfo_SoftwareFeatures.DiscardUnknown(m)
}

var xxx_messageInfo_SoftwareFeatures proto.InternalMessageInfo

func (m *SoftwareFeatures) GetAvailable() []string {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *SoftwareFeatures) GetUnavailable() []string {
	if m != nil {
		return m.Unavailable
	}
	return nil
}

type SysInfoStateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysInfoStateRequest) Reset()         { *m = SysInfoStateRequest{} }
func (m *SysInfoStateRequest) String() string { return proto.CompactTextString(m) }
func (*SysInfoStateRequest) ProtoMessage()    {}
func (*SysInfoStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_810bb274fc749e19, []int{3}
}

func (m *SysInfoStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysInfoStateRequest.Unmarshal(m, b)
}
func (m *SysInfoStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysInfoStateRequest.Marshal(b, m, deterministic)
}
func (m *SysInfoStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysInfoStateRequest.Merge(m, src)
}
func (m *SysInfoStateRequest) XXX_Size() int {
	return xxx_messageInfo_SysInfoStateRequest.Size(m)
}
func (m *SysInfoStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SysInfoStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SysInfoStateRequest proto.InternalMessageInfo

type GetSysInfoStateResult struct {
	State                *SysInfoState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Warnings             []string      `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetSysInfoStateResult) Reset()         { *m = GetSysInfoStateResult{} }
func (m *GetSysInfoStateResult) String() string { return proto.CompactTextString(m) }
func (*GetSysInfoStateResult) ProtoMessage()    {}
func (*GetSysInfoStateResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_810bb274fc749e19, []int{4}
}

func (m *GetSysInfoStateResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSysInfoStateResult.Unmarshal(m, b)
}
func (m *GetSysInfoStateResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSysInfoStateResult.Marshal(b, m, deterministic)
}
func (m *GetSysInfoStateResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSysInfoStateResult.Merge(m, src)
}
func (m *GetSysInfoStateResult) XXX_Size() int {
	return xxx_messageInfo_GetSysInfoStateResult.Size(m)
}
func (m *GetSysInfoStateResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSysInfoStateResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetSysInfoStateResult proto.InternalMessageInfo

func (m *GetSysInfoStateResult) GetState() *SysInfoState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *GetSysInfoStateResult) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type SysInfoState struct {
	LogInodeSizes        map[uint64]int64 `protobuf:"bytes,1,rep,name=log_inode_sizes,json=logInodeSizes,proto3" json:"log_inode_sizes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	JournaldCursor       string           `protobuf:"bytes,2,opt,name=journald_cursor,json=journaldCursor,proto3" json:"journald_cursor,omitempty"`
	MinidumpPaths        []string         `protobuf:"bytes,3,rep,name=minidump_paths,json=minidumpPaths,proto3" json:"minidump_paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SysInfoState) Reset()         { *m = SysInfoState{} }
func (m *SysInfoState) String() string { return proto.CompactTextString(m) }
func (*SysInfoState) ProtoMessage()    {}
func (*SysInfoState) Descriptor() ([]byte, []int) {
	return fileDescriptor_810bb274fc749e19, []int{5}
}

func (m *SysInfoState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysInfoState.Unmarshal(m, b)
}
func (m *SysInfoState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysInfoState.Marshal(b, m, deterministic)
}
func (m *SysInfoState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysInfoState.Merge(m, src)
}
func (m *SysInfoState) XXX_Size() int {
	return xxx_messageInfo_SysInfoState.Size(m)
}
func (m *SysInfoState) XXX_DiscardUnknown() {
	xxx_messageInfo_SysInfoState.DiscardUnknown(m)
}

var xxx_messageInfo_SysInfoState proto.InternalMessageInfo

func (m *SysInfoState) GetLogInodeSizes() map[uint64]int64 {
	if m != nil {
		return m.LogInodeSizes
	}
	return nil
}

func (m *SysInfoState) GetJournaldCursor() string {
	if m != nil {
		return m.JournaldCursor
	}
	return ""
}

func (m *SysInfoState) GetMinidumpPaths() []string {
	if m != nil {
		return m.MinidumpPaths
	}
	return nil
}

func init() {
	proto.RegisterType((*DUTInfoRequest)(nil), "tast.core.DUTInfoRequest")
	proto.RegisterType((*DUTInfoResponse)(nil), "tast.core.DUTInfoResponse")
	proto.RegisterType((*SoftwareFeatures)(nil), "tast.core.SoftwareFeatures")
	proto.RegisterType((*SysInfoStateRequest)(nil), "tast.core.SysInfoStateRequest")
	proto.RegisterType((*GetSysInfoStateResult)(nil), "tast.core.GetSysInfoStateResult")
	proto.RegisterType((*SysInfoState)(nil), "tast.core.SysInfoState")
	proto.RegisterMapType((map[uint64]int64)(nil), "tast.core.SysInfoState.LogInodeSizesEntry")
}

func init() { proto.RegisterFile("local_runner.proto", fileDescriptor_810bb274fc749e19) }

var fileDescriptor_810bb274fc749e19 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5d, 0x6f, 0x12, 0x41,
	0x14, 0xed, 0x82, 0xd5, 0x72, 0x29, 0x50, 0x07, 0x89, 0x88, 0x46, 0x71, 0x13, 0x95, 0x98, 0xb8,
	0x24, 0xf4, 0xc5, 0xf8, 0x64, 0xda, 0x5a, 0x6d, 0xe2, 0x83, 0x19, 0xec, 0x8b, 0x2f, 0x9b, 0x61,
	0xb9, 0xd0, 0xd5, 0x61, 0x06, 0x67, 0x66, 0xa9, 0xf8, 0x9b, 0xfa, 0xf3, 0xfc, 0x01, 0x66, 0x66,
	0x16, 0xba, 0xd0, 0xf6, 0x6d, 0xef, 0x39, 0x67, 0xef, 0xc7, 0xb9, 0x73, 0x81, 0x70, 0x99, 0x30,
	0x1e, 0xab, 0x4c, 0x08, 0x54, 0xd1, 0x5c, 0x49, 0x23, 0x49, 0xc5, 0x30, 0x6d, 0xa2, 0x44, 0x2a,
	0xec, 0x34, 0xc7, 0xb8, 0x48, 0x13, 0xec, 0x27, 0x52, 0x4c, 0xd2, 0xa9, 0xe7, 0x43, 0x0e, 0xf5,
	0x93, 0xf3, 0xef, 0x67, 0x62, 0x22, 0x29, 0xfe, 0xce, 0x50, 0x1b, 0xf2, 0x1a, 0x1a, 0xf8, 0xc7,
	0x28, 0x16, 0x67, 0x1a, 0xe3, 0x09, 0x67, 0x53, 0xdd, 0x0e, 0xba, 0xe5, 0x5e, 0x85, 0xd6, 0x1c,
	0x7c, 0xae, 0xf1, 0xd4, 0x82, 0x64, 0x00, 0x2d, 0xe5, 0x7f, 0x89, 0x7d, 0xe2, 0xd8, 0x27, 0x6e,
	0x97, 0xba, 0x41, 0x6f, 0x8f, 0x36, 0x73, 0xf2, 0xc4, 0x71, 0xc7, 0x8e, 0x0a, 0xaf, 0x02, 0x68,
	0xac, 0xcb, 0xe9, 0xb9, 0x14, 0x1a, 0xc9, 0x17, 0x78, 0xa8, 0xe5, 0xc4, 0x5c, 0x32, 0x85, 0xf1,
	0x04, 0x99, 0xc9, 0x14, 0xda, 0x8a, 0x41, 0xaf, 0x3a, 0x78, 0x1a, 0xad, 0xbb, 0x8f, 0x86, 0xb9,
	0xe6, 0x34, 0x97, 0xd0, 0x03, 0xbd, 0x85, 0x90, 0x43, 0xa8, 0xdd, 0xec, 0xa4, 0x3a, 0xa8, 0x47,
	0x1e, 0x8d, 0x7c, 0x13, 0x74, 0x7f, 0x5c, 0x68, 0x89, 0x74, 0x60, 0xef, 0x92, 0x29, 0x91, 0x8a,
	0xa9, 0x6e, 0x97, 0xdd, 0x9c, 0xeb, 0x38, 0xa4, 0x70, 0xb0, 0x5d, 0x96, 0x3c, 0x83, 0x0a, 0x5b,
	0xb0, 0x94, 0xb3, 0x11, 0xc7, 0xdc, 0x98, 0x6b, 0x80, 0x74, 0xa1, 0x9a, 0x89, 0x6b, 0xbe, 0xe4,
	0xf8, 0x22, 0x14, 0xb6, 0xa0, 0x39, 0x5c, 0x6a, 0xeb, 0xc0, 0xd0, 0x30, 0x83, 0xb9, 0xeb, 0xe1,
	0x08, 0x5a, 0x9f, 0xd1, 0x6c, 0x32, 0x3a, 0xe3, 0x86, 0xbc, 0x83, 0x5d, 0x6d, 0xc3, 0xdc, 0x92,
	0xc7, 0x45, 0x4b, 0x8a, 0x6a, 0xaf, 0xda, 0x18, 0xa7, 0xb4, 0x35, 0xce, 0xbf, 0x00, 0xf6, 0x8b,
	0xff, 0x10, 0x0a, 0x0d, 0x2e, 0xa7, 0x71, 0x2a, 0xe4, 0x18, 0x63, 0x9d, 0xfe, 0x45, 0xbf, 0xea,
	0xea, 0xe0, 0xed, 0x1d, 0x55, 0xa2, 0xaf, 0x72, 0x7a, 0x66, 0xd5, 0x43, 0x2b, 0xfe, 0x24, 0x8c,
	0x5a, 0xd2, 0x1a, 0x2f, 0x62, 0xe4, 0x0d, 0x34, 0x7e, 0xca, 0x4c, 0x09, 0xc6, 0xc7, 0x71, 0x92,
	0x29, 0x2d, 0x95, 0x5b, 0x43, 0x85, 0xd6, 0x57, 0xf0, 0xb1, 0x43, 0xc9, 0x2b, 0xa8, 0xcf, 0x52,
	0x91, 0x8e, 0xb3, 0xd9, 0x3c, 0x9e, 0x33, 0x73, 0xb1, 0xb2, 0xbf, 0xb6, 0x42, 0xbf, 0x59, 0xb0,
	0xf3, 0x11, 0xc8, 0xcd, 0xa2, 0xe4, 0x00, 0xca, 0xbf, 0x70, 0xe9, 0x3c, 0xb9, 0x47, 0xed, 0x27,
	0x79, 0x04, 0xbb, 0x0b, 0xc6, 0x33, 0x74, 0xd5, 0xca, 0xd4, 0x07, 0x1f, 0x4a, 0xef, 0x83, 0xc1,
	0x55, 0x60, 0x53, 0x24, 0x8c, 0x53, 0x77, 0x18, 0x43, 0x54, 0x76, 0xfd, 0xe4, 0x08, 0x1e, 0xe4,
	0x4f, 0x91, 0x3c, 0x29, 0x8c, 0xbb, 0x79, 0x0d, 0x9d, 0xce, 0x6d, 0x94, 0x7f, 0xb9, 0xe1, 0x0e,
	0xa1, 0x5b, 0x86, 0x3e, 0xbf, 0x6b, 0x3b, 0x79, 0xb6, 0x6e, 0x81, 0xbf, 0x75, 0xdd, 0xe1, 0xce,
	0xd1, 0xcb, 0x1f, 0x2f, 0x92, 0x0b, 0x25, 0x67, 0x69, 0x36, 0x93, 0xba, 0x6f, 0xf5, 0xfd, 0x54,
	0x18, 0xb4, 0xd6, 0xf5, 0xfd, 0x69, 0x8f, 0xee, 0xbb, 0xdb, 0x3d, 0xfc, 0x1f, 0x00, 0x00, 0xff,
	0xff, 0x35, 0x14, 0x1c, 0x0a, 0xf1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocalRunnerServiceClient is the client API for LocalRunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocalRunnerServiceClient interface {
	DUTInfo(ctx context.Context, in *DUTInfoRequest, opts ...grpc.CallOption) (*DUTInfoResponse, error)
	SysInfoState(ctx context.Context, in *SysInfoStateRequest, opts ...grpc.CallOption) (*GetSysInfoStateResult, error)
}

type localRunnerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLocalRunnerServiceClient(cc *grpc.ClientConn) LocalRunnerServiceClient {
	return &localRunnerServiceClient{cc}
}

func (c *localRunnerServiceClient) DUTInfo(ctx context.Context, in *DUTInfoRequest, opts ...grpc.CallOption) (*DUTInfoResponse, error) {
	out := new(DUTInfoResponse)
	err := c.cc.Invoke(ctx, "/tast.core.LocalRunnerService/DUTInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localRunnerServiceClient) SysInfoState(ctx context.Context, in *SysInfoStateRequest, opts ...grpc.CallOption) (*GetSysInfoStateResult, error) {
	out := new(GetSysInfoStateResult)
	err := c.cc.Invoke(ctx, "/tast.core.LocalRunnerService/SysInfoState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalRunnerServiceServer is the server API for LocalRunnerService service.
type LocalRunnerServiceServer interface {
	DUTInfo(context.Context, *DUTInfoRequest) (*DUTInfoResponse, error)
	SysInfoState(context.Context, *SysInfoStateRequest) (*GetSysInfoStateResult, error)
}

// UnimplementedLocalRunnerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLocalRunnerServiceServer struct {
}

func (*UnimplementedLocalRunnerServiceServer) DUTInfo(ctx context.Context, req *DUTInfoRequest) (*DUTInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DUTInfo not implemented")
}
func (*UnimplementedLocalRunnerServiceServer) SysInfoState(ctx context.Context, req *SysInfoStateRequest) (*GetSysInfoStateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SysInfoState not implemented")
}

func RegisterLocalRunnerServiceServer(s *grpc.Server, srv LocalRunnerServiceServer) {
	s.RegisterService(&_LocalRunnerService_serviceDesc, srv)
}

func _LocalRunnerService_DUTInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DUTInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalRunnerServiceServer).DUTInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.core.LocalRunnerService/DUTInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalRunnerServiceServer).DUTInfo(ctx, req.(*DUTInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalRunnerService_SysInfoState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SysInfoStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalRunnerServiceServer).SysInfoState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.core.LocalRunnerService/SysInfoState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalRunnerServiceServer).SysInfoState(ctx, req.(*SysInfoStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LocalRunnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.core.LocalRunnerService",
	HandlerType: (*LocalRunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DUTInfo",
			Handler:    _LocalRunnerService_DUTInfo_Handler,
		},
		{
			MethodName: "SysInfoState",
			Handler:    _LocalRunnerService_SysInfoState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "local_runner.proto",
}
