// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tastcore.proto

package runner

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DelegateRequest struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelegateRequest) Reset()         { *m = DelegateRequest{} }
func (m *DelegateRequest) String() string { return proto.CompactTextString(m) }
func (*DelegateRequest) ProtoMessage()    {}
func (*DelegateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef0902557ab46459, []int{0}
}

func (m *DelegateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegateRequest.Unmarshal(m, b)
}
func (m *DelegateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegateRequest.Marshal(b, m, deterministic)
}
func (m *DelegateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegateRequest.Merge(m, src)
}
func (m *DelegateRequest) XXX_Size() int {
	return xxx_messageInfo_DelegateRequest.Size(m)
}
func (m *DelegateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelegateRequest proto.InternalMessageInfo

func (m *DelegateRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type DelegateResponse struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelegateResponse) Reset()         { *m = DelegateResponse{} }
func (m *DelegateResponse) String() string { return proto.CompactTextString(m) }
func (*DelegateResponse) ProtoMessage()    {}
func (*DelegateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef0902557ab46459, []int{1}
}

func (m *DelegateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegateResponse.Unmarshal(m, b)
}
func (m *DelegateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegateResponse.Marshal(b, m, deterministic)
}
func (m *DelegateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegateResponse.Merge(m, src)
}
func (m *DelegateResponse) XXX_Size() int {
	return xxx_messageInfo_DelegateResponse.Size(m)
}
func (m *DelegateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelegateResponse proto.InternalMessageInfo

func (m *DelegateResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*DelegateRequest)(nil), "tast.core.DelegateRequest")
	proto.RegisterType((*DelegateResponse)(nil), "tast.core.DelegateResponse")
}

func init() { proto.RegisterFile("tastcore.proto", fileDescriptor_ef0902557ab46459) }

var fileDescriptor_ef0902557ab46459 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x49, 0x2c, 0x2e,
	0x49, 0xce, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xf1, 0xf5, 0x40,
	0x02, 0x4a, 0xda, 0x5c, 0xfc, 0x2e, 0xa9, 0x39, 0xa9, 0xe9, 0x89, 0x25, 0xa9, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x12, 0x5c, 0xec, 0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92, 0x0e, 0x97, 0x00, 0x42, 0x71, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0x2a, 0x6e, 0xd5, 0x46, 0x51, 0x5c, 0xfc, 0x21, 0x89, 0xc5, 0x25, 0xce, 0xf9,
	0x45, 0xa9, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xee, 0x5c, 0x1c, 0x30, 0x03, 0x84,
	0xa4, 0xf4, 0xe0, 0xae, 0xd0, 0x43, 0x73, 0x82, 0x94, 0x34, 0x56, 0x39, 0x88, 0x8d, 0x4a, 0x0c,
	0x06, 0x8c, 0x4e, 0x8a, 0x51, 0xf2, 0xc9, 0x19, 0x45, 0xf9, 0xb9, 0x99, 0xa5, 0xb9, 0xf9, 0xc5,
	0xfa, 0x20, 0xc5, 0xfa, 0x99, 0x79, 0x25, 0xa9, 0x45, 0x79, 0x89, 0x39, 0xfa, 0x45, 0xa5, 0x79,
	0x79, 0xa9, 0x45, 0x49, 0x6c, 0x60, 0xbf, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x31, 0x37,
	0xf4, 0xab, 0xfd, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TastCoreServiceClient is the client API for TastCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TastCoreServiceClient interface {
	Delegate(ctx context.Context, in *DelegateRequest, opts ...grpc.CallOption) (TastCoreService_DelegateClient, error)
}

type tastCoreServiceClient struct {
	cc *grpc.ClientConn
}

func NewTastCoreServiceClient(cc *grpc.ClientConn) TastCoreServiceClient {
	return &tastCoreServiceClient{cc}
}

func (c *tastCoreServiceClient) Delegate(ctx context.Context, in *DelegateRequest, opts ...grpc.CallOption) (TastCoreService_DelegateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TastCoreService_serviceDesc.Streams[0], "/tast.core.TastCoreService/Delegate", opts...)
	if err != nil {
		return nil, err
	}
	x := &tastCoreServiceDelegateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TastCoreService_DelegateClient interface {
	Recv() (*DelegateResponse, error)
	grpc.ClientStream
}

type tastCoreServiceDelegateClient struct {
	grpc.ClientStream
}

func (x *tastCoreServiceDelegateClient) Recv() (*DelegateResponse, error) {
	m := new(DelegateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TastCoreServiceServer is the server API for TastCoreService service.
type TastCoreServiceServer interface {
	Delegate(*DelegateRequest, TastCoreService_DelegateServer) error
}

// UnimplementedTastCoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTastCoreServiceServer struct {
}

func (*UnimplementedTastCoreServiceServer) Delegate(req *DelegateRequest, srv TastCoreService_DelegateServer) error {
	return status.Errorf(codes.Unimplemented, "method Delegate not implemented")
}

func RegisterTastCoreServiceServer(s *grpc.Server, srv TastCoreServiceServer) {
	s.RegisterService(&_TastCoreService_serviceDesc, srv)
}

func _TastCoreService_Delegate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DelegateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TastCoreServiceServer).Delegate(m, &tastCoreServiceDelegateServer{stream})
}

type TastCoreService_DelegateServer interface {
	Send(*DelegateResponse) error
	grpc.ServerStream
}

type tastCoreServiceDelegateServer struct {
	grpc.ServerStream
}

func (x *tastCoreServiceDelegateServer) Send(m *DelegateResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _TastCoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.core.TastCoreService",
	HandlerType: (*TastCoreServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Delegate",
			Handler:       _TastCoreService_Delegate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tastcore.proto",
}
