// Code generated by protoc-gen-go. DO NOT EDIT.
// source: features.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	api "go.chromium.org/chromiumos/config/go/api"
	device "go.chromium.org/chromiumos/infra/proto/go/device"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceInfo_SOC int32

const (
	DeviceInfo_SOC_UNSPECIFIED DeviceInfo_SOC = 0
	// Aka AML-Y
	DeviceInfo_SOC_AMBERLAKE_Y   DeviceInfo_SOC = 1
	DeviceInfo_SOC_APOLLO_LAKE   DeviceInfo_SOC = 2
	DeviceInfo_SOC_BAY_TRAIL     DeviceInfo_SOC = 3
	DeviceInfo_SOC_BRASWELL      DeviceInfo_SOC = 4
	DeviceInfo_SOC_BROADWELL     DeviceInfo_SOC = 5
	DeviceInfo_SOC_CANNON_LAKE_Y DeviceInfo_SOC = 6
	DeviceInfo_SOC_COMET_LAKE_U  DeviceInfo_SOC = 7
	DeviceInfo_SOC_EXYNOS_5250   DeviceInfo_SOC = 8
	DeviceInfo_SOC_EXYNOS_5420   DeviceInfo_SOC = 9
	// Aka GLK
	DeviceInfo_SOC_GEMINI_LAKE DeviceInfo_SOC = 10
	DeviceInfo_SOC_HASWELL     DeviceInfo_SOC = 11
	DeviceInfo_SOC_ICE_LAKE_Y  DeviceInfo_SOC = 12
	DeviceInfo_SOC_IVY_BRIDGE  DeviceInfo_SOC = 13
	DeviceInfo_SOC_KABYLAKE_U  DeviceInfo_SOC = 14
	// KabyLake U refresh
	DeviceInfo_SOC_KABYLAKE_U_R   DeviceInfo_SOC = 15
	DeviceInfo_SOC_KABYLAKE_Y     DeviceInfo_SOC = 16
	DeviceInfo_SOC_MT8173         DeviceInfo_SOC = 17
	DeviceInfo_SOC_MT8176         DeviceInfo_SOC = 18
	DeviceInfo_SOC_MT8183         DeviceInfo_SOC = 19
	DeviceInfo_SOC_PICASSO        DeviceInfo_SOC = 20
	DeviceInfo_SOC_PINE_TRAIL     DeviceInfo_SOC = 21
	DeviceInfo_SOC_RK3288         DeviceInfo_SOC = 22
	DeviceInfo_SOC_RK3399         DeviceInfo_SOC = 23
	DeviceInfo_SOC_SANDY_BRIDGE   DeviceInfo_SOC = 24
	DeviceInfo_SOC_SDM845         DeviceInfo_SOC = 25
	DeviceInfo_SOC_SKYLAKE_U      DeviceInfo_SOC = 26
	DeviceInfo_SOC_SKYLAKE_Y      DeviceInfo_SOC = 27
	DeviceInfo_SOC_STONEY_RIDGE   DeviceInfo_SOC = 28
	DeviceInfo_SOC_TEGRA_K1       DeviceInfo_SOC = 29
	DeviceInfo_SOC_WHISKEY_LAKE_U DeviceInfo_SOC = 30
	DeviceInfo_SOC_SC7180         DeviceInfo_SOC = 31
	DeviceInfo_SOC_JASPER_LAKE    DeviceInfo_SOC = 32
	DeviceInfo_SOC_TIGER_LAKE     DeviceInfo_SOC = 33
	DeviceInfo_SOC_MT8192         DeviceInfo_SOC = 34
	DeviceInfo_SOC_ALDER_LAKE     DeviceInfo_SOC = 35
	DeviceInfo_SOC_SC7280         DeviceInfo_SOC = 36
	DeviceInfo_SOC_MT8195         DeviceInfo_SOC = 37
)

var DeviceInfo_SOC_name = map[int32]string{
	0:  "SOC_UNSPECIFIED",
	1:  "SOC_AMBERLAKE_Y",
	2:  "SOC_APOLLO_LAKE",
	3:  "SOC_BAY_TRAIL",
	4:  "SOC_BRASWELL",
	5:  "SOC_BROADWELL",
	6:  "SOC_CANNON_LAKE_Y",
	7:  "SOC_COMET_LAKE_U",
	8:  "SOC_EXYNOS_5250",
	9:  "SOC_EXYNOS_5420",
	10: "SOC_GEMINI_LAKE",
	11: "SOC_HASWELL",
	12: "SOC_ICE_LAKE_Y",
	13: "SOC_IVY_BRIDGE",
	14: "SOC_KABYLAKE_U",
	15: "SOC_KABYLAKE_U_R",
	16: "SOC_KABYLAKE_Y",
	17: "SOC_MT8173",
	18: "SOC_MT8176",
	19: "SOC_MT8183",
	20: "SOC_PICASSO",
	21: "SOC_PINE_TRAIL",
	22: "SOC_RK3288",
	23: "SOC_RK3399",
	24: "SOC_SANDY_BRIDGE",
	25: "SOC_SDM845",
	26: "SOC_SKYLAKE_U",
	27: "SOC_SKYLAKE_Y",
	28: "SOC_STONEY_RIDGE",
	29: "SOC_TEGRA_K1",
	30: "SOC_WHISKEY_LAKE_U",
	31: "SOC_SC7180",
	32: "SOC_JASPER_LAKE",
	33: "SOC_TIGER_LAKE",
	34: "SOC_MT8192",
	35: "SOC_ALDER_LAKE",
	36: "SOC_SC7280",
	37: "SOC_MT8195",
}

var DeviceInfo_SOC_value = map[string]int32{
	"SOC_UNSPECIFIED":    0,
	"SOC_AMBERLAKE_Y":    1,
	"SOC_APOLLO_LAKE":    2,
	"SOC_BAY_TRAIL":      3,
	"SOC_BRASWELL":       4,
	"SOC_BROADWELL":      5,
	"SOC_CANNON_LAKE_Y":  6,
	"SOC_COMET_LAKE_U":   7,
	"SOC_EXYNOS_5250":    8,
	"SOC_EXYNOS_5420":    9,
	"SOC_GEMINI_LAKE":    10,
	"SOC_HASWELL":        11,
	"SOC_ICE_LAKE_Y":     12,
	"SOC_IVY_BRIDGE":     13,
	"SOC_KABYLAKE_U":     14,
	"SOC_KABYLAKE_U_R":   15,
	"SOC_KABYLAKE_Y":     16,
	"SOC_MT8173":         17,
	"SOC_MT8176":         18,
	"SOC_MT8183":         19,
	"SOC_PICASSO":        20,
	"SOC_PINE_TRAIL":     21,
	"SOC_RK3288":         22,
	"SOC_RK3399":         23,
	"SOC_SANDY_BRIDGE":   24,
	"SOC_SDM845":         25,
	"SOC_SKYLAKE_U":      26,
	"SOC_SKYLAKE_Y":      27,
	"SOC_STONEY_RIDGE":   28,
	"SOC_TEGRA_K1":       29,
	"SOC_WHISKEY_LAKE_U": 30,
	"SOC_SC7180":         31,
	"SOC_JASPER_LAKE":    32,
	"SOC_TIGER_LAKE":     33,
	"SOC_MT8192":         34,
	"SOC_ALDER_LAKE":     35,
	"SOC_SC7280":         36,
	"SOC_MT8195":         37,
}

func (x DeviceInfo_SOC) String() string {
	return proto.EnumName(DeviceInfo_SOC_name, int32(x))
}

func (DeviceInfo_SOC) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{3, 0}
}

// Features represents a set of features available for tests.
type Features struct {
	// CheckDeps indicates whether to skip tests whose dependencies are not
	// satisfied by available features.
	CheckDeps            bool              `protobuf:"varint,5,opt,name=check_deps,json=checkDeps,proto3" json:"check_deps,omitempty"`
	Software             *SoftwareFeatures `protobuf:"bytes,1,opt,name=software,proto3" json:"software,omitempty"`
	Hardware             *HardwareFeatures `protobuf:"bytes,2,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Vars                 map[string]string `protobuf:"bytes,3,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MaybeMissingVars     string            `protobuf:"bytes,4,opt,name=maybe_missing_vars,json=maybeMissingVars,proto3" json:"maybe_missing_vars,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Features) Reset()         { *m = Features{} }
func (m *Features) String() string { return proto.CompactTextString(m) }
func (*Features) ProtoMessage()    {}
func (*Features) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{0}
}

func (m *Features) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Features.Unmarshal(m, b)
}
func (m *Features) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Features.Marshal(b, m, deterministic)
}
func (m *Features) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Features.Merge(m, src)
}
func (m *Features) XXX_Size() int {
	return xxx_messageInfo_Features.Size(m)
}
func (m *Features) XXX_DiscardUnknown() {
	xxx_messageInfo_Features.DiscardUnknown(m)
}

var xxx_messageInfo_Features proto.InternalMessageInfo

func (m *Features) GetCheckDeps() bool {
	if m != nil {
		return m.CheckDeps
	}
	return false
}

func (m *Features) GetSoftware() *SoftwareFeatures {
	if m != nil {
		return m.Software
	}
	return nil
}

func (m *Features) GetHardware() *HardwareFeatures {
	if m != nil {
		return m.Hardware
	}
	return nil
}

func (m *Features) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

func (m *Features) GetMaybeMissingVars() string {
	if m != nil {
		return m.MaybeMissingVars
	}
	return ""
}

// SoftwareFeatures represents a set of software features available for the
// image being tested.
type SoftwareFeatures struct {
	Available            []string `protobuf:"bytes,1,rep,name=available,proto3" json:"available,omitempty"`
	Unavailable          []string `protobuf:"bytes,2,rep,name=unavailable,proto3" json:"unavailable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SoftwareFeatures) Reset()         { *m = SoftwareFeatures{} }
func (m *SoftwareFeatures) String() string { return proto.CompactTextString(m) }
func (*SoftwareFeatures) ProtoMessage()    {}
func (*SoftwareFeatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{1}
}

func (m *SoftwareFeatures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SoftwareFeatures.Unmarshal(m, b)
}
func (m *SoftwareFeatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SoftwareFeatures.Marshal(b, m, deterministic)
}
func (m *SoftwareFeatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SoftwareFeatures.Merge(m, src)
}
func (m *SoftwareFeatures) XXX_Size() int {
	return xxx_messageInfo_SoftwareFeatures.Size(m)
}
func (m *SoftwareFeatures) XXX_DiscardUnknown() {
	xxx_messageInfo_SoftwareFeatures.DiscardUnknown(m)
}

var xxx_messageInfo_SoftwareFeatures proto.InternalMessageInfo

func (m *SoftwareFeatures) GetAvailable() []string {
	if m != nil {
		return m.Available
	}
	return nil
}

func (m *SoftwareFeatures) GetUnavailable() []string {
	if m != nil {
		return m.Unavailable
	}
	return nil
}

// DeviceConfigIds is the labels given to DUT based on the hardware model or
// platform name. These information is fetched from the DUT at runtime by the
// framework.
type DeviceConfigIds struct {
	Model                string   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceConfigIds) Reset()         { *m = DeviceConfigIds{} }
func (m *DeviceConfigIds) String() string { return proto.CompactTextString(m) }
func (*DeviceConfigIds) ProtoMessage()    {}
func (*DeviceConfigIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{2}
}

func (m *DeviceConfigIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceConfigIds.Unmarshal(m, b)
}
func (m *DeviceConfigIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceConfigIds.Marshal(b, m, deterministic)
}
func (m *DeviceConfigIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceConfigIds.Merge(m, src)
}
func (m *DeviceConfigIds) XXX_Size() int {
	return xxx_messageInfo_DeviceConfigIds.Size(m)
}
func (m *DeviceConfigIds) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceConfigIds.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceConfigIds proto.InternalMessageInfo

func (m *DeviceConfigIds) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *DeviceConfigIds) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *DeviceConfigIds) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

// A message that replaces device.Config from device/config.proto.
type DeviceInfo struct {
	Ids                  *DeviceConfigIds `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	Soc                  DeviceInfo_SOC   `protobuf:"varint,2,opt,name=soc,proto3,enum=tast.core.DeviceInfo_SOC" json:"soc,omitempty"`
	HasBattery           bool             `protobuf:"varint,3,opt,name=has_battery,json=hasBattery,proto3" json:"has_battery,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{3}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetIds() *DeviceConfigIds {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *DeviceInfo) GetSoc() DeviceInfo_SOC {
	if m != nil {
		return m.Soc
	}
	return DeviceInfo_SOC_UNSPECIFIED
}

func (m *DeviceInfo) GetHasBattery() bool {
	if m != nil {
		return m.HasBattery
	}
	return false
}

// HardwareFeatures represents a set of hardware features available for the
// device model being tested.
type HardwareFeatures struct {
	HardwareFeatures       *api.HardwareFeatures `protobuf:"bytes,1,opt,name=hardware_features,json=hardwareFeatures,proto3" json:"hardware_features,omitempty"`
	DeprecatedDeviceConfig *device.Config        `protobuf:"bytes,2,opt,name=deprecated_device_config,json=deprecatedDeviceConfig,proto3" json:"deprecated_device_config,omitempty"`
	DeviceInfo             *DeviceInfo           `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *HardwareFeatures) Reset()         { *m = HardwareFeatures{} }
func (m *HardwareFeatures) String() string { return proto.CompactTextString(m) }
func (*HardwareFeatures) ProtoMessage()    {}
func (*HardwareFeatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216f05915163cdf, []int{4}
}

func (m *HardwareFeatures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HardwareFeatures.Unmarshal(m, b)
}
func (m *HardwareFeatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HardwareFeatures.Marshal(b, m, deterministic)
}
func (m *HardwareFeatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HardwareFeatures.Merge(m, src)
}
func (m *HardwareFeatures) XXX_Size() int {
	return xxx_messageInfo_HardwareFeatures.Size(m)
}
func (m *HardwareFeatures) XXX_DiscardUnknown() {
	xxx_messageInfo_HardwareFeatures.DiscardUnknown(m)
}

var xxx_messageInfo_HardwareFeatures proto.InternalMessageInfo

func (m *HardwareFeatures) GetHardwareFeatures() *api.HardwareFeatures {
	if m != nil {
		return m.HardwareFeatures
	}
	return nil
}

func (m *HardwareFeatures) GetDeprecatedDeviceConfig() *device.Config {
	if m != nil {
		return m.DeprecatedDeviceConfig
	}
	return nil
}

func (m *HardwareFeatures) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("tast.core.DeviceInfo_SOC", DeviceInfo_SOC_name, DeviceInfo_SOC_value)
	proto.RegisterType((*Features)(nil), "tast.core.Features")
	proto.RegisterMapType((map[string]string)(nil), "tast.core.Features.VarsEntry")
	proto.RegisterType((*SoftwareFeatures)(nil), "tast.core.SoftwareFeatures")
	proto.RegisterType((*DeviceConfigIds)(nil), "tast.core.DeviceConfigIds")
	proto.RegisterType((*DeviceInfo)(nil), "tast.core.DeviceInfo")
	proto.RegisterType((*HardwareFeatures)(nil), "tast.core.HardwareFeatures")
}

func init() { proto.RegisterFile("features.proto", fileDescriptor_2216f05915163cdf) }

var fileDescriptor_2216f05915163cdf = []byte{
	// 903 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x95, 0xdd, 0x72, 0xda, 0x46,
	0x14, 0xc7, 0x0b, 0xc2, 0x2e, 0x1c, 0x12, 0xbc, 0x5e, 0x7f, 0x94, 0x90, 0xb8, 0x21, 0x24, 0x9d,
	0x32, 0xd3, 0x8c, 0xb0, 0x21, 0x8e, 0x71, 0xef, 0x04, 0x28, 0xb6, 0xc2, 0x87, 0x98, 0x15, 0x49,
	0xaa, 0xde, 0x68, 0x16, 0x24, 0x8c, 0x26, 0x20, 0x31, 0x92, 0xec, 0x0e, 0x0f, 0xd6, 0xc7, 0xe9,
	0x7d, 0x2f, 0xfb, 0x08, 0x1d, 0xad, 0xb4, 0x42, 0xc1, 0xb9, 0xd3, 0xf9, 0xed, 0xff, 0x7f, 0xf6,
	0xec, 0x9e, 0xd9, 0x23, 0x28, 0xcd, 0x2d, 0x1a, 0xdc, 0x7b, 0x96, 0x2f, 0xae, 0x3d, 0x37, 0x70,
	0x71, 0x21, 0xa0, 0x7e, 0x20, 0xce, 0x5c, 0xcf, 0xaa, 0xbc, 0x99, 0x2d, 0x3c, 0x77, 0x65, 0xdf,
	0xaf, 0x5c, 0xbf, 0x31, 0x73, 0x9d, 0xb9, 0x7d, 0xd7, 0xa0, 0x6b, 0xbb, 0x11, 0xb8, 0x6b, 0x77,
	0xe9, 0xde, 0x6d, 0x22, 0x43, 0xe5, 0xc8, 0xb4, 0x1e, 0xec, 0x99, 0x15, 0x2b, 0x22, 0x58, 0xfb,
	0x3b, 0x0b, 0xf9, 0x0f, 0x71, 0x62, 0x7c, 0x06, 0x30, 0x5b, 0x58, 0xb3, 0xaf, 0x86, 0x69, 0xad,
	0xfd, 0xf2, 0x5e, 0x35, 0x53, 0xcf, 0x93, 0x02, 0x23, 0x3d, 0x6b, 0xed, 0xe3, 0x2b, 0xc8, 0xfb,
	0xee, 0x3c, 0xf8, 0x8b, 0x7a, 0x56, 0x39, 0x53, 0xcd, 0xd4, 0x8b, 0xcd, 0xe7, 0x62, 0x52, 0x84,
	0xa8, 0xc5, 0x4b, 0x3c, 0x1b, 0x49, 0xc4, 0xa1, 0x71, 0x41, 0x3d, 0x93, 0x19, 0xb3, 0x8f, 0x8c,
	0xb7, 0xf1, 0xd2, 0xd6, 0xc8, 0xc5, 0xf8, 0x02, 0x72, 0x0f, 0xd4, 0xf3, 0xcb, 0x42, 0x55, 0xa8,
	0x17, 0x9b, 0x67, 0x29, 0x13, 0x17, 0x8b, 0x9f, 0xa9, 0xe7, 0xcb, 0x4e, 0xe0, 0x6d, 0x08, 0x93,
	0xe2, 0xb7, 0x80, 0x57, 0x74, 0x33, 0xb5, 0x8c, 0x95, 0xed, 0xfb, 0xb6, 0x73, 0x67, 0xb0, 0x04,
	0xb9, 0x6a, 0xa6, 0x5e, 0x20, 0x88, 0xad, 0x0c, 0xa3, 0x85, 0xd0, 0x58, 0xb9, 0x82, 0x42, 0x92,
	0x00, 0x23, 0x10, 0xbe, 0x5a, 0x1b, 0x76, 0xb4, 0x02, 0x09, 0x3f, 0xf1, 0x31, 0xec, 0x3d, 0xd0,
	0xe5, 0x7d, 0x54, 0x75, 0x81, 0x44, 0xc1, 0xef, 0xd9, 0x76, 0xa6, 0x46, 0x00, 0xed, 0x1e, 0x18,
	0xbf, 0x80, 0x02, 0x7d, 0xa0, 0xf6, 0x92, 0x4e, 0x97, 0xe1, 0x05, 0x09, 0xf5, 0x02, 0xd9, 0x02,
	0x5c, 0x85, 0xe2, 0xbd, 0xb3, 0x5d, 0xcf, 0xb2, 0xf5, 0x34, 0xaa, 0xe9, 0x70, 0xd0, 0x63, 0x2d,
	0xea, 0xb2, 0x0e, 0x29, 0xa6, 0x1f, 0x16, 0xb0, 0x72, 0x4d, 0x6b, 0x19, 0x17, 0x15, 0x05, 0xb8,
	0x02, 0xf9, 0xf5, 0x92, 0x06, 0x73, 0xd7, 0x5b, 0xc5, 0x95, 0x25, 0x71, 0xe8, 0x98, 0x7a, 0xd4,
	0x31, 0xcb, 0x42, 0xe4, 0x60, 0x41, 0xed, 0xdf, 0x7d, 0x80, 0x28, 0xb7, 0xe2, 0xcc, 0x5d, 0xfc,
	0x16, 0x04, 0xdb, 0xf4, 0xe3, 0x26, 0x56, 0x52, 0xd7, 0xba, 0xb3, 0x3f, 0x09, 0x65, 0xf8, 0x37,
	0x10, 0x7c, 0x77, 0xc6, 0x76, 0x2a, 0x35, 0x9f, 0x3d, 0x52, 0x87, 0x19, 0x45, 0x4d, 0xed, 0x92,
	0x50, 0x85, 0x5f, 0x42, 0x71, 0x41, 0x7d, 0x63, 0x4a, 0x83, 0xc0, 0xf2, 0x36, 0xac, 0x8a, 0x3c,
	0x81, 0x05, 0xf5, 0x3b, 0x11, 0xa9, 0xfd, 0xb3, 0x07, 0x82, 0xa6, 0x76, 0xf1, 0x11, 0x1c, 0x68,
	0x6a, 0xd7, 0xf8, 0x34, 0xd2, 0xc6, 0x72, 0x57, 0xf9, 0xa0, 0xc8, 0x3d, 0xf4, 0x03, 0x87, 0xd2,
	0xb0, 0x23, 0x93, 0x81, 0xd4, 0x97, 0x0d, 0x1d, 0x65, 0x12, 0x38, 0x56, 0x07, 0x03, 0xd5, 0x08,
	0x31, 0xca, 0xe2, 0x43, 0x78, 0x1a, 0xc2, 0x8e, 0xa4, 0x1b, 0x13, 0x22, 0x29, 0x03, 0x24, 0x60,
	0x04, 0x4f, 0x18, 0x22, 0x92, 0xf6, 0x45, 0x1e, 0x0c, 0x50, 0x2e, 0x11, 0x11, 0x55, 0xea, 0x31,
	0xb4, 0x87, 0x4f, 0xe0, 0x30, 0x44, 0x5d, 0x69, 0x34, 0x52, 0x47, 0x46, 0xbc, 0xc7, 0x3e, 0x3e,
	0x06, 0xc4, 0xb0, 0x3a, 0x94, 0x27, 0x11, 0xfd, 0x84, 0x7e, 0xe4, 0x3b, 0xcb, 0x7f, 0xe8, 0x23,
	0x55, 0x33, 0x2e, 0x9b, 0x97, 0xe7, 0x28, 0xbf, 0x0b, 0xdf, 0x35, 0xcf, 0x51, 0x81, 0xc3, 0x1b,
	0x79, 0xa8, 0x8c, 0x94, 0xa8, 0x46, 0xc0, 0x07, 0x50, 0x0c, 0xe1, 0x6d, 0x5c, 0x4f, 0x11, 0x63,
	0x28, 0x85, 0x40, 0xe9, 0xca, 0x7c, 0xe7, 0x27, 0x09, 0xfb, 0xac, 0x1b, 0x1d, 0xa2, 0xf4, 0x6e,
	0x64, 0xf4, 0x94, 0xb3, 0xbe, 0xd4, 0xd1, 0xe3, 0x5a, 0x4a, 0xbc, 0xc2, 0x2d, 0x33, 0x08, 0x3a,
	0x78, 0xa4, 0xd4, 0x11, 0xc2, 0x25, 0x80, 0x90, 0x0d, 0x27, 0xed, 0x8b, 0xab, 0x16, 0x3a, 0xfc,
	0x26, 0x7e, 0x8f, 0x70, 0x3a, 0x6e, 0xb7, 0xd0, 0x11, 0x2f, 0x73, 0xac, 0x74, 0x25, 0x4d, 0x53,
	0xd1, 0x31, 0x4f, 0x3a, 0x56, 0x46, 0x72, 0x7c, 0xb9, 0x27, 0xdc, 0x44, 0xfa, 0xad, 0x66, 0xbb,
	0x8d, 0x4e, 0x53, 0x71, 0xeb, 0xfa, 0x1a, 0xfd, 0xc4, 0xcb, 0xd3, 0xa4, 0x51, 0x2f, 0x39, 0x48,
	0x99, 0xab, 0xb4, 0xde, 0xb0, 0xfd, 0xee, 0x12, 0x3d, 0xe3, 0x0d, 0xd1, 0xfa, 0xfc, 0x5c, 0x95,
	0x5d, 0xa4, 0xa3, 0xe7, 0x49, 0xae, 0x89, 0x3a, 0x92, 0x75, 0x23, 0xca, 0xf5, 0x82, 0xb7, 0x77,
	0x22, 0xdf, 0x10, 0xc9, 0xe8, 0x5f, 0xa0, 0x33, 0x7c, 0x0a, 0x38, 0x24, 0x5f, 0x6e, 0x15, 0xad,
	0x2f, 0xeb, 0xbc, 0x6d, 0x3f, 0x27, 0xbb, 0x76, 0xaf, 0x2e, 0xda, 0xe7, 0xe8, 0x25, 0x6f, 0xce,
	0x47, 0x49, 0x1b, 0xcb, 0x24, 0x6a, 0x4e, 0x95, 0x1f, 0x72, 0xa2, 0xdc, 0x70, 0xf6, 0x2a, 0x7d,
	0x33, 0xd7, 0x4d, 0x54, 0xe3, 0x1a, 0x69, 0xd0, 0xe3, 0x9a, 0xd7, 0xa9, 0xe4, 0xcd, 0xf6, 0x39,
	0x7a, 0xf3, 0x8d, 0xe7, 0x12, 0xfd, 0x52, 0xfb, 0x2f, 0x03, 0x68, 0x77, 0xa4, 0xe1, 0x09, 0x1c,
	0xf2, 0xa1, 0x66, 0xf0, 0x39, 0x1e, 0x3f, 0xbf, 0x5f, 0xc5, 0xed, 0xf4, 0x16, 0xe3, 0xd9, 0x4c,
	0xd7, 0xf6, 0xe3, 0xb1, 0x88, 0x16, 0xbb, 0x59, 0x6f, 0xa1, 0x6c, 0x5a, 0x6b, 0xcf, 0x9a, 0xd1,
	0xc0, 0x32, 0x8d, 0x68, 0xbc, 0x1b, 0x51, 0x8a, 0x78, 0xce, 0x96, 0xc4, 0x88, 0x8a, 0xd1, 0x93,
	0x26, 0xa7, 0x5b, 0x7d, 0xfa, 0xa9, 0xe3, 0xf7, 0x50, 0x8c, 0xed, 0xb6, 0x33, 0x77, 0xd9, 0xb8,
	0x2c, 0x36, 0x4f, 0xbe, 0xfb, 0xd4, 0x09, 0x98, 0xc9, 0xf7, 0xc7, 0x5c, 0x5e, 0x40, 0xb9, 0xce,
	0xeb, 0x3f, 0x5f, 0xa5, 0xfe, 0x40, 0xa1, 0xa9, 0x61, 0x3b, 0x81, 0xe5, 0x39, 0x74, 0xd9, 0x60,
	0xbf, 0x99, 0x99, 0xbb, 0x9c, 0xee, 0xb3, 0xaf, 0xd6, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x16,
	0xfb, 0xa6, 0xce, 0xc8, 0x06, 0x00, 0x00,
}
