// Code generated by protoc-gen-go. DO NOT EDIT.
// source: handshake.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HandshakeRequest contains parameters needed to initialize a gRPC server.
// The message is sent in a raw format since gRPC connection is not ready before
// handshake.
type HandshakeRequest struct {
	// Whether to initialize user-defined gRPC services.
	NeedUserServices     bool              `protobuf:"varint,1,opt,name=need_user_services,json=needUserServices,proto3" json:"need_user_services,omitempty"`
	EntityInitParams     *EntityInitParams `protobuf:"bytes,2,opt,name=entity_init_params,json=entityInitParams,proto3" json:"entity_init_params,omitempty"`
	RunnerInitParams     *RunnerInitParams `protobuf:"bytes,3,opt,name=runner_init_params,json=runnerInitParams,proto3" json:"runner_init_params,omitempty"`
	BundleInitParams     *BundleInitParams `protobuf:"bytes,4,opt,name=bundle_init_params,json=bundleInitParams,proto3" json:"bundle_init_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HandshakeRequest) Reset()         { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()    {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{0}
}

func (m *HandshakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeRequest.Unmarshal(m, b)
}
func (m *HandshakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeRequest.Marshal(b, m, deterministic)
}
func (m *HandshakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeRequest.Merge(m, src)
}
func (m *HandshakeRequest) XXX_Size() int {
	return xxx_messageInfo_HandshakeRequest.Size(m)
}
func (m *HandshakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeRequest proto.InternalMessageInfo

func (m *HandshakeRequest) GetNeedUserServices() bool {
	if m != nil {
		return m.NeedUserServices
	}
	return false
}

func (m *HandshakeRequest) GetEntityInitParams() *EntityInitParams {
	if m != nil {
		return m.EntityInitParams
	}
	return nil
}

func (m *HandshakeRequest) GetRunnerInitParams() *RunnerInitParams {
	if m != nil {
		return m.RunnerInitParams
	}
	return nil
}

func (m *HandshakeRequest) GetBundleInitParams() *BundleInitParams {
	if m != nil {
		return m.BundleInitParams
	}
	return nil
}

// EntityInitParams contains parameters needed to initialize user-defined
// entities.
type EntityInitParams struct {
	// Runtime variables.
	Vars                 map[string]string `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EntityInitParams) Reset()         { *m = EntityInitParams{} }
func (m *EntityInitParams) String() string { return proto.CompactTextString(m) }
func (*EntityInitParams) ProtoMessage()    {}
func (*EntityInitParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{1}
}

func (m *EntityInitParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityInitParams.Unmarshal(m, b)
}
func (m *EntityInitParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityInitParams.Marshal(b, m, deterministic)
}
func (m *EntityInitParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityInitParams.Merge(m, src)
}
func (m *EntityInitParams) XXX_Size() int {
	return xxx_messageInfo_EntityInitParams.Size(m)
}
func (m *EntityInitParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityInitParams.DiscardUnknown(m)
}

var xxx_messageInfo_EntityInitParams proto.InternalMessageInfo

func (m *EntityInitParams) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

// HandshakeResponse is a response to an HandshakeRequest message.
// The message is sent in a raw format since gRPC connection is not ready before
// handshake.
type HandshakeResponse struct {
	// Set if an error occurred.
	Error                *HandshakeError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HandshakeResponse) Reset()         { *m = HandshakeResponse{} }
func (m *HandshakeResponse) String() string { return proto.CompactTextString(m) }
func (*HandshakeResponse) ProtoMessage()    {}
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{2}
}

func (m *HandshakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeResponse.Unmarshal(m, b)
}
func (m *HandshakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeResponse.Marshal(b, m, deterministic)
}
func (m *HandshakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeResponse.Merge(m, src)
}
func (m *HandshakeResponse) XXX_Size() int {
	return xxx_messageInfo_HandshakeResponse.Size(m)
}
func (m *HandshakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeResponse proto.InternalMessageInfo

func (m *HandshakeResponse) GetError() *HandshakeError {
	if m != nil {
		return m.Error
	}
	return nil
}

// HandshakeError describes a failed handshake result.
type HandshakeError struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandshakeError) Reset()         { *m = HandshakeError{} }
func (m *HandshakeError) String() string { return proto.CompactTextString(m) }
func (*HandshakeError) ProtoMessage()    {}
func (*HandshakeError) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{3}
}

func (m *HandshakeError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandshakeError.Unmarshal(m, b)
}
func (m *HandshakeError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandshakeError.Marshal(b, m, deterministic)
}
func (m *HandshakeError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandshakeError.Merge(m, src)
}
func (m *HandshakeError) XXX_Size() int {
	return xxx_messageInfo_HandshakeError.Size(m)
}
func (m *HandshakeError) XXX_DiscardUnknown() {
	xxx_messageInfo_HandshakeError.DiscardUnknown(m)
}

var xxx_messageInfo_HandshakeError proto.InternalMessageInfo

func (m *HandshakeError) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// RunnerInitParams contains information needed to initialize test runners.
type RunnerInitParams struct {
	// A file path glob that matches test bundle executables.
	// Example: "/usr/local/libexec/tast/bundles/local/*"
	BundleGlob           string   `protobuf:"bytes,1,opt,name=bundle_glob,json=bundleGlob,proto3" json:"bundle_glob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunnerInitParams) Reset()         { *m = RunnerInitParams{} }
func (m *RunnerInitParams) String() string { return proto.CompactTextString(m) }
func (*RunnerInitParams) ProtoMessage()    {}
func (*RunnerInitParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{4}
}

func (m *RunnerInitParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunnerInitParams.Unmarshal(m, b)
}
func (m *RunnerInitParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunnerInitParams.Marshal(b, m, deterministic)
}
func (m *RunnerInitParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunnerInitParams.Merge(m, src)
}
func (m *RunnerInitParams) XXX_Size() int {
	return xxx_messageInfo_RunnerInitParams.Size(m)
}
func (m *RunnerInitParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RunnerInitParams.DiscardUnknown(m)
}

var xxx_messageInfo_RunnerInitParams proto.InternalMessageInfo

func (m *RunnerInitParams) GetBundleGlob() string {
	if m != nil {
		return m.BundleGlob
	}
	return ""
}

type BundleInitParams struct {
	// BundleConfigs represents all the bundles to run.
	// For bundle servers, this must be a singleton.
	BundleConfig         *BundleConfig `protobuf:"bytes,1,opt,name=bundle_config,json=bundleConfig,proto3" json:"bundle_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BundleInitParams) Reset()         { *m = BundleInitParams{} }
func (m *BundleInitParams) String() string { return proto.CompactTextString(m) }
func (*BundleInitParams) ProtoMessage()    {}
func (*BundleInitParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{5}
}

func (m *BundleInitParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleInitParams.Unmarshal(m, b)
}
func (m *BundleInitParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleInitParams.Marshal(b, m, deterministic)
}
func (m *BundleInitParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleInitParams.Merge(m, src)
}
func (m *BundleInitParams) XXX_Size() int {
	return xxx_messageInfo_BundleInitParams.Size(m)
}
func (m *BundleInitParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleInitParams.DiscardUnknown(m)
}

var xxx_messageInfo_BundleInitParams proto.InternalMessageInfo

func (m *BundleInitParams) GetBundleConfig() *BundleConfig {
	if m != nil {
		return m.BundleConfig
	}
	return nil
}

type BundleConfig struct {
	// PrimaryTarget is the target device for remote tests.
	PrimaryTarget        *TargetDevice         `protobuf:"bytes,1,opt,name=primary_target,json=primaryTarget,proto3" json:"primary_target,omitempty"`
	CompanionDuts        map[string]*DUTConfig `protobuf:"bytes,2,rep,name=companion_duts,json=companionDuts,proto3" json:"companion_duts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MetaTestConfig       *MetaTestConfig       `protobuf:"bytes,3,opt,name=meta_test_config,json=metaTestConfig,proto3" json:"meta_test_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BundleConfig) Reset()         { *m = BundleConfig{} }
func (m *BundleConfig) String() string { return proto.CompactTextString(m) }
func (*BundleConfig) ProtoMessage()    {}
func (*BundleConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{6}
}

func (m *BundleConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleConfig.Unmarshal(m, b)
}
func (m *BundleConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleConfig.Marshal(b, m, deterministic)
}
func (m *BundleConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleConfig.Merge(m, src)
}
func (m *BundleConfig) XXX_Size() int {
	return xxx_messageInfo_BundleConfig.Size(m)
}
func (m *BundleConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BundleConfig proto.InternalMessageInfo

func (m *BundleConfig) GetPrimaryTarget() *TargetDevice {
	if m != nil {
		return m.PrimaryTarget
	}
	return nil
}

func (m *BundleConfig) GetCompanionDuts() map[string]*DUTConfig {
	if m != nil {
		return m.CompanionDuts
	}
	return nil
}

func (m *BundleConfig) GetMetaTestConfig() *MetaTestConfig {
	if m != nil {
		return m.MetaTestConfig
	}
	return nil
}

// TargetDevice represents a local bundle on which remote tests invoke services.
type TargetDevice struct {
	// DutConfig describes the DUT containing local bundles.
	DutConfig *DUTConfig `protobuf:"bytes,1,opt,name=dut_config,json=dutConfig,proto3" json:"dut_config,omitempty"`
	// BundleDir represents the directory on which the target bundle exists.
	BundleDir            string   `protobuf:"bytes,2,opt,name=bundle_dir,json=bundleDir,proto3" json:"bundle_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetDevice) Reset()         { *m = TargetDevice{} }
func (m *TargetDevice) String() string { return proto.CompactTextString(m) }
func (*TargetDevice) ProtoMessage()    {}
func (*TargetDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{7}
}

func (m *TargetDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetDevice.Unmarshal(m, b)
}
func (m *TargetDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetDevice.Marshal(b, m, deterministic)
}
func (m *TargetDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetDevice.Merge(m, src)
}
func (m *TargetDevice) XXX_Size() int {
	return xxx_messageInfo_TargetDevice.Size(m)
}
func (m *TargetDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetDevice.DiscardUnknown(m)
}

var xxx_messageInfo_TargetDevice proto.InternalMessageInfo

func (m *TargetDevice) GetDutConfig() *DUTConfig {
	if m != nil {
		return m.DutConfig
	}
	return nil
}

func (m *TargetDevice) GetBundleDir() string {
	if m != nil {
		return m.BundleDir
	}
	return ""
}

// DUTConfig describes a DUT.
type DUTConfig struct {
	// SshConfig contains information needed to connect to the DUT via SSH.
	SshConfig *SSHConfig `protobuf:"bytes,1,opt,name=ssh_config,json=sshConfig,proto3" json:"ssh_config,omitempty"`
	// TlwName contains the name of the DUT recognized by the TLW service.
	// This must be set when TLW API is used.
	TlwName              string   `protobuf:"bytes,2,opt,name=tlw_name,json=tlwName,proto3" json:"tlw_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DUTConfig) Reset()         { *m = DUTConfig{} }
func (m *DUTConfig) String() string { return proto.CompactTextString(m) }
func (*DUTConfig) ProtoMessage()    {}
func (*DUTConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{8}
}

func (m *DUTConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DUTConfig.Unmarshal(m, b)
}
func (m *DUTConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DUTConfig.Marshal(b, m, deterministic)
}
func (m *DUTConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DUTConfig.Merge(m, src)
}
func (m *DUTConfig) XXX_Size() int {
	return xxx_messageInfo_DUTConfig.Size(m)
}
func (m *DUTConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DUTConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DUTConfig proto.InternalMessageInfo

func (m *DUTConfig) GetSshConfig() *SSHConfig {
	if m != nil {
		return m.SshConfig
	}
	return nil
}

func (m *DUTConfig) GetTlwName() string {
	if m != nil {
		return m.TlwName
	}
	return ""
}

// SSHConfig contains information needed to connect to the DUT via SSH.
type SSHConfig struct {
	// Target is a connection spec as [<user>@]host[:<port>].
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// KeyFile is a path to the SSH private key to use to connect to the target.
	KeyFile string `protobuf:"bytes,2,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	// KeyDir is a path to the directory containing SSH private keys
	// (typically $HOME/.ssh).
	KeyDir               string   `protobuf:"bytes,3,opt,name=key_dir,json=keyDir,proto3" json:"key_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSHConfig) Reset()         { *m = SSHConfig{} }
func (m *SSHConfig) String() string { return proto.CompactTextString(m) }
func (*SSHConfig) ProtoMessage()    {}
func (*SSHConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{9}
}

func (m *SSHConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSHConfig.Unmarshal(m, b)
}
func (m *SSHConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSHConfig.Marshal(b, m, deterministic)
}
func (m *SSHConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSHConfig.Merge(m, src)
}
func (m *SSHConfig) XXX_Size() int {
	return xxx_messageInfo_SSHConfig.Size(m)
}
func (m *SSHConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SSHConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SSHConfig proto.InternalMessageInfo

func (m *SSHConfig) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *SSHConfig) GetKeyFile() string {
	if m != nil {
		return m.KeyFile
	}
	return ""
}

func (m *SSHConfig) GetKeyDir() string {
	if m != nil {
		return m.KeyDir
	}
	return ""
}

// MetaTestConfig contains parameters needed by meta tests (tests that
// exercise Tast itself).
type MetaTestConfig struct {
	// TastPath contains the path to the tast binary that was executed to initiate
	// testing.
	TastPath string `protobuf:"bytes,1,opt,name=tast_path,json=tastPath,proto3" json:"tast_path,omitempty"`
	// RunFlags contains a subset of the flags that were passed to the "tast run"
	// command. The included flags are ones that are necessary for core
	// functionality, e.g. paths to binaries used by the tast process and
	// credentials for reconnecting to the DUT.
	RunFlags             []string `protobuf:"bytes,2,rep,name=run_flags,json=runFlags,proto3" json:"run_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaTestConfig) Reset()         { *m = MetaTestConfig{} }
func (m *MetaTestConfig) String() string { return proto.CompactTextString(m) }
func (*MetaTestConfig) ProtoMessage()    {}
func (*MetaTestConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a77305914d5d202f, []int{10}
}

func (m *MetaTestConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaTestConfig.Unmarshal(m, b)
}
func (m *MetaTestConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaTestConfig.Marshal(b, m, deterministic)
}
func (m *MetaTestConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaTestConfig.Merge(m, src)
}
func (m *MetaTestConfig) XXX_Size() int {
	return xxx_messageInfo_MetaTestConfig.Size(m)
}
func (m *MetaTestConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaTestConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MetaTestConfig proto.InternalMessageInfo

func (m *MetaTestConfig) GetTastPath() string {
	if m != nil {
		return m.TastPath
	}
	return ""
}

func (m *MetaTestConfig) GetRunFlags() []string {
	if m != nil {
		return m.RunFlags
	}
	return nil
}

func init() {
	proto.RegisterType((*HandshakeRequest)(nil), "tast.core.HandshakeRequest")
	proto.RegisterType((*EntityInitParams)(nil), "tast.core.EntityInitParams")
	proto.RegisterMapType((map[string]string)(nil), "tast.core.EntityInitParams.VarsEntry")
	proto.RegisterType((*HandshakeResponse)(nil), "tast.core.HandshakeResponse")
	proto.RegisterType((*HandshakeError)(nil), "tast.core.HandshakeError")
	proto.RegisterType((*RunnerInitParams)(nil), "tast.core.RunnerInitParams")
	proto.RegisterType((*BundleInitParams)(nil), "tast.core.BundleInitParams")
	proto.RegisterType((*BundleConfig)(nil), "tast.core.BundleConfig")
	proto.RegisterMapType((map[string]*DUTConfig)(nil), "tast.core.BundleConfig.CompanionDutsEntry")
	proto.RegisterType((*TargetDevice)(nil), "tast.core.TargetDevice")
	proto.RegisterType((*DUTConfig)(nil), "tast.core.DUTConfig")
	proto.RegisterType((*SSHConfig)(nil), "tast.core.SSHConfig")
	proto.RegisterType((*MetaTestConfig)(nil), "tast.core.MetaTestConfig")
}

func init() { proto.RegisterFile("handshake.proto", fileDescriptor_a77305914d5d202f) }

var fileDescriptor_a77305914d5d202f = []byte{
	// 665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdd, 0x6a, 0xdb, 0x4a,
	0x10, 0xc6, 0x76, 0x92, 0x63, 0x8d, 0x13, 0x1f, 0x9d, 0x25, 0x9c, 0xfc, 0x51, 0x9a, 0xaa, 0x14,
	0x4c, 0x28, 0x36, 0x38, 0x17, 0xfd, 0xa1, 0xf4, 0x22, 0x71, 0xd2, 0xa4, 0xd0, 0x92, 0x2a, 0x3f,
	0x85, 0xf6, 0x42, 0xac, 0xed, 0x89, 0xb5, 0x58, 0xda, 0x75, 0x77, 0x57, 0x09, 0x7a, 0x81, 0xbe,
	0x47, 0x5f, 0xa4, 0xcf, 0x56, 0x76, 0xb5, 0x36, 0xb2, 0x9d, 0xf4, 0x4e, 0xf3, 0xcd, 0x7c, 0xdf,
	0xcc, 0xce, 0x7c, 0x08, 0xfe, 0x8d, 0x29, 0x1f, 0xaa, 0x98, 0x8e, 0xb1, 0x3d, 0x91, 0x42, 0x0b,
	0xe2, 0x69, 0xaa, 0x74, 0x7b, 0x20, 0x24, 0x06, 0xbf, 0xaa, 0xe0, 0x9f, 0x4d, 0xd3, 0x21, 0xfe,
	0xc8, 0x50, 0x69, 0xf2, 0x12, 0x08, 0x47, 0x1c, 0x46, 0x99, 0x42, 0x19, 0x29, 0x94, 0x77, 0x6c,
	0x80, 0x6a, 0xbb, 0xb2, 0x5f, 0x69, 0xd5, 0x43, 0xdf, 0x64, 0xae, 0x15, 0xca, 0x4b, 0x87, 0x93,
	0x73, 0x20, 0xc8, 0x35, 0xd3, 0x79, 0xc4, 0x38, 0xd3, 0xd1, 0x84, 0x4a, 0x9a, 0xaa, 0xed, 0xea,
	0x7e, 0xa5, 0xd5, 0xe8, 0xee, 0xb5, 0x67, 0xad, 0xda, 0x27, 0xb6, 0xe8, 0x9c, 0x33, 0x7d, 0x61,
	0x4b, 0x42, 0x1f, 0x17, 0x10, 0x23, 0x25, 0x33, 0xce, 0x51, 0xce, 0x49, 0xd5, 0x96, 0xa4, 0x42,
	0x5b, 0x54, 0x96, 0x92, 0x0b, 0x88, 0x91, 0xea, 0x67, 0x7c, 0x98, 0xe0, 0x9c, 0xd4, 0xca, 0x92,
	0xd4, 0x91, 0x2d, 0x2a, 0x4b, 0xf5, 0x17, 0x90, 0xe0, 0x67, 0x05, 0xfc, 0xc5, 0xe1, 0xc9, 0x1b,
	0x58, 0xb9, 0xa3, 0xd2, 0x6c, 0xa5, 0xd6, 0x6a, 0x74, 0x5f, 0xfc, 0xe5, 0x9d, 0xed, 0x1b, 0x2a,
	0xd5, 0x09, 0xd7, 0x32, 0x0f, 0x2d, 0x65, 0xf7, 0x15, 0x78, 0x33, 0x88, 0xf8, 0x50, 0x1b, 0x63,
	0x6e, 0x97, 0xeb, 0x85, 0xe6, 0x93, 0x6c, 0xc2, 0xea, 0x1d, 0x4d, 0x32, 0xb4, 0x2b, 0xf4, 0xc2,
	0x22, 0x78, 0x5b, 0x7d, 0x5d, 0x09, 0x7a, 0xf0, 0x5f, 0xe9, 0x56, 0x6a, 0x22, 0xb8, 0x42, 0xd2,
	0x81, 0x55, 0x94, 0x52, 0x48, 0x2b, 0xd1, 0xe8, 0xee, 0x94, 0x26, 0x99, 0x15, 0x9f, 0x98, 0x82,
	0xb0, 0xa8, 0x0b, 0x5a, 0xd0, 0x9c, 0x4f, 0x90, 0xff, 0x61, 0x4d, 0x22, 0x55, 0x82, 0xbb, 0x31,
	0x5c, 0x14, 0x1c, 0x82, 0xbf, 0xb8, 0x69, 0xf2, 0x14, 0x1a, 0x6e, 0xaf, 0xa3, 0x44, 0xf4, 0x1d,
	0x01, 0x0a, 0xe8, 0x43, 0x22, 0xfa, 0xc1, 0x05, 0xf8, 0x8b, 0x3b, 0x25, 0xef, 0x60, 0xc3, 0x91,
	0x06, 0x82, 0xdf, 0xb2, 0x91, 0x9b, 0x75, 0x6b, 0xe9, 0x0e, 0xc7, 0x36, 0x1d, 0xae, 0xf7, 0x4b,
	0x51, 0xf0, 0xbb, 0x0a, 0xeb, 0xe5, 0x34, 0x79, 0x0f, 0xcd, 0x89, 0x64, 0x29, 0x95, 0x79, 0xa4,
	0xa9, 0x1c, 0xa1, 0x7e, 0x40, 0xef, 0xca, 0x26, 0x7a, 0x68, 0x3c, 0x1a, 0x6e, 0xb8, 0xf2, 0x02,
	0x24, 0x5f, 0xa0, 0x39, 0x10, 0xe9, 0x84, 0x72, 0x26, 0x78, 0x34, 0xcc, 0xb4, 0x71, 0xab, 0xb9,
	0xe2, 0xc1, 0x23, 0xf3, 0xb4, 0x8f, 0xa7, 0xd5, 0xbd, 0x4c, 0xbb, 0x53, 0x6e, 0x0c, 0xca, 0x18,
	0x39, 0x06, 0x3f, 0x45, 0x4d, 0x23, 0x8d, 0x4a, 0x4f, 0x1f, 0x59, 0x5b, 0x3a, 0xc8, 0x27, 0xd4,
	0xf4, 0x0a, 0x95, 0x76, 0xcf, 0x6c, 0xa6, 0x73, 0xf1, 0xee, 0x0d, 0x90, 0xe5, 0x4e, 0x0f, 0x38,
	0xe4, 0xa0, 0xec, 0x90, 0x46, 0x77, 0xb3, 0xd4, 0xa1, 0x77, 0x7d, 0xe5, 0xc4, 0x4b, 0xbe, 0xe9,
	0xc3, 0x7a, 0x79, 0x1d, 0xe4, 0x10, 0x60, 0x98, 0xe9, 0xf9, 0x5b, 0x3c, 0x2c, 0xe2, 0x0d, 0x33,
	0x37, 0x1c, 0x79, 0x02, 0xee, 0xca, 0xd1, 0x90, 0x49, 0xe7, 0x4d, 0xaf, 0x40, 0x7a, 0x4c, 0x06,
	0xdf, 0xc1, 0x9b, 0xd1, 0x4c, 0x03, 0xa5, 0xe2, 0xc7, 0x1b, 0x5c, 0x5e, 0x9e, 0x4d, 0x1b, 0x28,
	0x15, 0x3b, 0xd2, 0x0e, 0xd4, 0x75, 0x72, 0x1f, 0x71, 0x9a, 0x4e, 0xad, 0xff, 0x8f, 0x4e, 0xee,
	0x3f, 0xd3, 0x14, 0x83, 0xaf, 0xe0, 0xcd, 0x28, 0xc6, 0xad, 0xa5, 0xab, 0x7b, 0xa1, 0x8b, 0x0c,
	0x7f, 0x8c, 0x79, 0x74, 0xcb, 0x92, 0x19, 0x7f, 0x8c, 0xf9, 0x29, 0x4b, 0x90, 0x6c, 0x81, 0xf9,
	0xb4, 0x83, 0xd7, 0x0a, 0xce, 0x18, 0x73, 0x33, 0xf5, 0x47, 0x68, 0xce, 0xdf, 0x84, 0xec, 0x81,
	0xfd, 0x3b, 0x46, 0x13, 0xaa, 0x63, 0xd7, 0xa0, 0x6e, 0x80, 0x0b, 0xaa, 0x63, 0x93, 0x94, 0x19,
	0x8f, 0x6e, 0x13, 0x3a, 0x2a, 0x3c, 0xe3, 0x85, 0x75, 0x99, 0xf1, 0x53, 0x13, 0x1f, 0x3d, 0xff,
	0xf6, 0x6c, 0x10, 0x4b, 0x91, 0xb2, 0x2c, 0x15, 0xaa, 0x63, 0x38, 0x1d, 0xc6, 0x35, 0x4a, 0x4e,
	0x93, 0x8e, 0xfd, 0xef, 0x0e, 0x44, 0xd2, 0x5f, 0xb3, 0x5f, 0x87, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x5e, 0x24, 0x9b, 0x6d, 0x94, 0x05, 0x00, 0x00,
}
