// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reports.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogStreamRequest struct {
	Test                 string   `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogStreamRequest) Reset()         { *m = LogStreamRequest{} }
func (m *LogStreamRequest) String() string { return proto.CompactTextString(m) }
func (*LogStreamRequest) ProtoMessage()    {}
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66b94ab03de429a8, []int{0}
}

func (m *LogStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogStreamRequest.Unmarshal(m, b)
}
func (m *LogStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogStreamRequest.Marshal(b, m, deterministic)
}
func (m *LogStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogStreamRequest.Merge(m, src)
}
func (m *LogStreamRequest) XXX_Size() int {
	return xxx_messageInfo_LogStreamRequest.Size(m)
}
func (m *LogStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogStreamRequest proto.InternalMessageInfo

func (m *LogStreamRequest) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

func (m *LogStreamRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReportResultRequest struct {
	Test                 string   `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	Errors               []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	SkipReason           string   `protobuf:"bytes,3,opt,name=SkipReason,proto3" json:"SkipReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportResultRequest) Reset()         { *m = ReportResultRequest{} }
func (m *ReportResultRequest) String() string { return proto.CompactTextString(m) }
func (*ReportResultRequest) ProtoMessage()    {}
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66b94ab03de429a8, []int{1}
}

func (m *ReportResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResultRequest.Unmarshal(m, b)
}
func (m *ReportResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResultRequest.Marshal(b, m, deterministic)
}
func (m *ReportResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResultRequest.Merge(m, src)
}
func (m *ReportResultRequest) XXX_Size() int {
	return xxx_messageInfo_ReportResultRequest.Size(m)
}
func (m *ReportResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResultRequest proto.InternalMessageInfo

func (m *ReportResultRequest) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

func (m *ReportResultRequest) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *ReportResultRequest) GetSkipReason() string {
	if m != nil {
		return m.SkipReason
	}
	return ""
}

type Error struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	File                 string   `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Line                 int32    `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Stack                string   `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_66b94ab03de429a8, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Error) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Error) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Error) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *Error) GetStack() string {
	if m != nil {
		return m.Stack
	}
	return ""
}

func init() {
	proto.RegisterType((*LogStreamRequest)(nil), "tast.core.LogStreamRequest")
	proto.RegisterType((*ReportResultRequest)(nil), "tast.core.ReportResultRequest")
	proto.RegisterType((*Error)(nil), "tast.core.Error")
}

func init() { proto.RegisterFile("reports.proto", fileDescriptor_66b94ab03de429a8) }

var fileDescriptor_66b94ab03de429a8 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xff, 0x69, 0x9b, 0xfe, 0xd5, 0xa3, 0x48, 0x95, 0x41, 0x55, 0xd4, 0x4a, 0x55, 0x08,
	0x4b, 0x26, 0x47, 0x2a, 0x1b, 0x23, 0xa2, 0x12, 0x03, 0x93, 0xbb, 0xb1, 0xb9, 0xe1, 0x5a, 0xac,
	0x26, 0x71, 0x6a, 0x5f, 0x06, 0x3e, 0x0a, 0xdf, 0x16, 0xc5, 0x2e, 0x51, 0x84, 0x80, 0xed, 0xf9,
	0xdd, 0xdd, 0xbb, 0xdc, 0x2f, 0x70, 0x69, 0xb0, 0xd6, 0x86, 0x2c, 0xaf, 0x8d, 0x26, 0xcd, 0x26,
	0x24, 0x2d, 0xf1, 0x5c, 0x1b, 0x5c, 0x2c, 0x0f, 0x5a, 0x1f, 0x0a, 0xcc, 0x5c, 0x61, 0xd7, 0xec,
	0x33, 0x2c, 0x6b, 0x7a, 0xf7, 0x7d, 0xc9, 0x3d, 0xcc, 0x9e, 0xf5, 0x61, 0x4b, 0x06, 0x65, 0x29,
	0xf0, 0xd4, 0xa0, 0x25, 0xc6, 0x60, 0x44, 0x68, 0x29, 0x0a, 0xe2, 0x20, 0x9d, 0x08, 0xa7, 0x5b,
	0xef, 0x55, 0x92, 0x8c, 0x06, 0x71, 0x90, 0x4e, 0x85, 0xd3, 0x89, 0x85, 0x2b, 0xe1, 0x96, 0x0a,
	0xb4, 0x4d, 0x41, 0x7f, 0x8d, 0xa7, 0x30, 0x46, 0x63, 0xb4, 0xb1, 0xd1, 0x20, 0x1e, 0xa6, 0x17,
	0xeb, 0x19, 0xef, 0xbe, 0x8f, 0x6f, 0xda, 0x82, 0x38, 0xd7, 0xd9, 0x0a, 0x60, 0x7b, 0x54, 0xb5,
	0x40, 0x69, 0x75, 0x15, 0x0d, 0x5d, 0x46, 0xcf, 0x49, 0x4e, 0x10, 0xba, 0x01, 0xb7, 0x46, 0x95,
	0xd8, 0xad, 0x51, 0x25, 0xb2, 0x39, 0x8c, 0x8d, 0x1f, 0x1c, 0x38, 0xf7, 0xfc, 0x6a, 0x7b, 0xf7,
	0xaa, 0xc0, 0x73, 0x9c, 0xd3, 0xad, 0x57, 0xa8, 0x0a, 0xa3, 0x51, 0x1c, 0xa4, 0xa1, 0x70, 0x9a,
	0x5d, 0x43, 0x68, 0x49, 0xe6, 0xc7, 0x28, 0x74, 0x8d, 0xfe, 0xb1, 0xfe, 0x08, 0xe0, 0xbf, 0x3f,
	0xd4, 0xb2, 0x47, 0x98, 0x74, 0xbc, 0xd8, 0xb2, 0x77, 0xc5, 0x77, 0x8a, 0x8b, 0x39, 0xf7, 0xdc,
	0xf9, 0x17, 0x77, 0xbe, 0x69, 0xb9, 0x27, 0xff, 0xd2, 0x80, 0x3d, 0xc1, 0xb4, 0x4f, 0x8e, 0xad,
	0x7a, 0x41, 0x3f, 0x20, 0xfd, 0x3d, 0xeb, 0xe1, 0xf6, 0xe5, 0x26, 0x7f, 0x33, 0xba, 0x54, 0x4d,
	0xa9, 0x6d, 0xd6, 0xa6, 0x64, 0xaa, 0x22, 0x34, 0x95, 0x2c, 0xfc, 0x0f, 0xcf, 0x75, 0xb1, 0x1b,
	0x3b, 0x75, 0xf7, 0x19, 0x00, 0x00, 0xff, 0xff, 0x73, 0x5f, 0x92, 0xef, 0x24, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReportsClient is the client API for Reports service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportsClient interface {
	// LogStream accepts a stream of log data.
	// The request should be called only once per client.
	LogStream(ctx context.Context, opts ...grpc.CallOption) (Reports_LogStreamClient, error)
	// ReportResults accepts test results from a client.
	// This request can be called multiple times per client.
	ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type reportsClient struct {
	cc *grpc.ClientConn
}

func NewReportsClient(cc *grpc.ClientConn) ReportsClient {
	return &reportsClient{cc}
}

func (c *reportsClient) LogStream(ctx context.Context, opts ...grpc.CallOption) (Reports_LogStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Reports_serviceDesc.Streams[0], "/tast.core.Reports/LogStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &reportsLogStreamClient{stream}
	return x, nil
}

type Reports_LogStreamClient interface {
	Send(*LogStreamRequest) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type reportsLogStreamClient struct {
	grpc.ClientStream
}

func (x *reportsLogStreamClient) Send(m *LogStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reportsLogStreamClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *reportsClient) ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/tast.core.Reports/ReportResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportsServer is the server API for Reports service.
type ReportsServer interface {
	// LogStream accepts a stream of log data.
	// The request should be called only once per client.
	LogStream(Reports_LogStreamServer) error
	// ReportResults accepts test results from a client.
	// This request can be called multiple times per client.
	ReportResult(context.Context, *ReportResultRequest) (*empty.Empty, error)
}

// UnimplementedReportsServer can be embedded to have forward compatible implementations.
type UnimplementedReportsServer struct {
}

func (*UnimplementedReportsServer) LogStream(srv Reports_LogStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LogStream not implemented")
}
func (*UnimplementedReportsServer) ReportResult(ctx context.Context, req *ReportResultRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResult not implemented")
}

func RegisterReportsServer(s *grpc.Server, srv ReportsServer) {
	s.RegisterService(&_Reports_serviceDesc, srv)
}

func _Reports_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReportsServer).LogStream(&reportsLogStreamServer{stream})
}

type Reports_LogStreamServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*LogStreamRequest, error)
	grpc.ServerStream
}

type reportsLogStreamServer struct {
	grpc.ServerStream
}

func (x *reportsLogStreamServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reportsLogStreamServer) Recv() (*LogStreamRequest, error) {
	m := new(LogStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Reports_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportsServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tast.core.Reports/ReportResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportsServer).ReportResult(ctx, req.(*ReportResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reports_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tast.core.Reports",
	HandlerType: (*ReportsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportResult",
			Handler:    _Reports_ReportResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LogStream",
			Handler:       _Reports_LogStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "reports.proto",
}
