// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testing.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EntityType describes a type of an entity.
type EntityType int32

const (
	EntityType_TEST    EntityType = 0
	EntityType_FIXTURE EntityType = 1
)

var EntityType_name = map[int32]string{
	0: "TEST",
	1: "FIXTURE",
}

var EntityType_value = map[string]int32{
	"TEST":    0,
	"FIXTURE": 1,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}

func (EntityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{0}
}

// ControlMessage represents an event that occurred during testing.
//
// Control messages are sent over a streaming channel to notify events in
// real time.
type ControlMessage struct {
	// Types that are valid to be assigned to Message:
	//	*ControlMessage_RunStart
	//	*ControlMessage_RunLog
	//	*ControlMessage_EntityStart
	//	*ControlMessage_EntityLog
	//	*ControlMessage_EntityError
	//	*ControlMessage_EntityEnd
	Message              isControlMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ControlMessage) Reset()         { *m = ControlMessage{} }
func (m *ControlMessage) String() string { return proto.CompactTextString(m) }
func (*ControlMessage) ProtoMessage()    {}
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{0}
}

func (m *ControlMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlMessage.Unmarshal(m, b)
}
func (m *ControlMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlMessage.Marshal(b, m, deterministic)
}
func (m *ControlMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlMessage.Merge(m, src)
}
func (m *ControlMessage) XXX_Size() int {
	return xxx_messageInfo_ControlMessage.Size(m)
}
func (m *ControlMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ControlMessage proto.InternalMessageInfo

type isControlMessage_Message interface {
	isControlMessage_Message()
}

type ControlMessage_RunStart struct {
	RunStart *RunStart `protobuf:"bytes,1,opt,name=run_start,json=runStart,proto3,oneof"`
}

type ControlMessage_RunLog struct {
	RunLog *RunLog `protobuf:"bytes,2,opt,name=run_log,json=runLog,proto3,oneof"`
}

type ControlMessage_EntityStart struct {
	EntityStart *EntityStart `protobuf:"bytes,3,opt,name=entity_start,json=entityStart,proto3,oneof"`
}

type ControlMessage_EntityLog struct {
	EntityLog *EntityLog `protobuf:"bytes,4,opt,name=entity_log,json=entityLog,proto3,oneof"`
}

type ControlMessage_EntityError struct {
	EntityError *EntityError `protobuf:"bytes,5,opt,name=entity_error,json=entityError,proto3,oneof"`
}

type ControlMessage_EntityEnd struct {
	EntityEnd *EntityEnd `protobuf:"bytes,6,opt,name=entity_end,json=entityEnd,proto3,oneof"`
}

func (*ControlMessage_RunStart) isControlMessage_Message() {}

func (*ControlMessage_RunLog) isControlMessage_Message() {}

func (*ControlMessage_EntityStart) isControlMessage_Message() {}

func (*ControlMessage_EntityLog) isControlMessage_Message() {}

func (*ControlMessage_EntityError) isControlMessage_Message() {}

func (*ControlMessage_EntityEnd) isControlMessage_Message() {}

func (m *ControlMessage) GetMessage() isControlMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ControlMessage) GetRunStart() *RunStart {
	if x, ok := m.GetMessage().(*ControlMessage_RunStart); ok {
		return x.RunStart
	}
	return nil
}

func (m *ControlMessage) GetRunLog() *RunLog {
	if x, ok := m.GetMessage().(*ControlMessage_RunLog); ok {
		return x.RunLog
	}
	return nil
}

func (m *ControlMessage) GetEntityStart() *EntityStart {
	if x, ok := m.GetMessage().(*ControlMessage_EntityStart); ok {
		return x.EntityStart
	}
	return nil
}

func (m *ControlMessage) GetEntityLog() *EntityLog {
	if x, ok := m.GetMessage().(*ControlMessage_EntityLog); ok {
		return x.EntityLog
	}
	return nil
}

func (m *ControlMessage) GetEntityError() *EntityError {
	if x, ok := m.GetMessage().(*ControlMessage_EntityError); ok {
		return x.EntityError
	}
	return nil
}

func (m *ControlMessage) GetEntityEnd() *EntityEnd {
	if x, ok := m.GetMessage().(*ControlMessage_EntityEnd); ok {
		return x.EntityEnd
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ControlMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ControlMessage_RunStart)(nil),
		(*ControlMessage_RunLog)(nil),
		(*ControlMessage_EntityStart)(nil),
		(*ControlMessage_EntityLog)(nil),
		(*ControlMessage_EntityError)(nil),
		(*ControlMessage_EntityEnd)(nil),
	}
}

// RunStart message is sent exactly once as the first message on a streaming
// channel to notify a testing plan.
type RunStart struct {
	// tests is a list of test names to be run. The list is sorted in the same
	// order as that of actual test execution.
	TestNames            []string `protobuf:"bytes,1,rep,name=test_names,json=testNames,proto3" json:"test_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunStart) Reset()         { *m = RunStart{} }
func (m *RunStart) String() string { return proto.CompactTextString(m) }
func (*RunStart) ProtoMessage()    {}
func (*RunStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{1}
}

func (m *RunStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunStart.Unmarshal(m, b)
}
func (m *RunStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunStart.Marshal(b, m, deterministic)
}
func (m *RunStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunStart.Merge(m, src)
}
func (m *RunStart) XXX_Size() int {
	return xxx_messageInfo_RunStart.Size(m)
}
func (m *RunStart) XXX_DiscardUnknown() {
	xxx_messageInfo_RunStart.DiscardUnknown(m)
}

var xxx_messageInfo_RunStart proto.InternalMessageInfo

func (m *RunStart) GetTestNames() []string {
	if m != nil {
		return m.TestNames
	}
	return nil
}

// RunLog message indicates that an informational log message not associated
// with an entity was produced.
type RunLog struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Text                 string               `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RunLog) Reset()         { *m = RunLog{} }
func (m *RunLog) String() string { return proto.CompactTextString(m) }
func (*RunLog) ProtoMessage()    {}
func (*RunLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{2}
}

func (m *RunLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunLog.Unmarshal(m, b)
}
func (m *RunLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunLog.Marshal(b, m, deterministic)
}
func (m *RunLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunLog.Merge(m, src)
}
func (m *RunLog) XXX_Size() int {
	return xxx_messageInfo_RunLog.Size(m)
}
func (m *RunLog) XXX_DiscardUnknown() {
	xxx_messageInfo_RunLog.DiscardUnknown(m)
}

var xxx_messageInfo_RunLog proto.InternalMessageInfo

func (m *RunLog) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *RunLog) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// EntityStart message marks the start of an entity run.
// EntityStart is sent even if an entity is to be skipped.
type EntityStart struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	EntityName           string               `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	EntityType           EntityType           `protobuf:"varint,3,opt,name=entity_type,json=entityType,proto3,enum=tast.core.EntityType" json:"entity_type,omitempty"`
	OutDir               string               `protobuf:"bytes,4,opt,name=out_dir,json=outDir,proto3" json:"out_dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EntityStart) Reset()         { *m = EntityStart{} }
func (m *EntityStart) String() string { return proto.CompactTextString(m) }
func (*EntityStart) ProtoMessage()    {}
func (*EntityStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{3}
}

func (m *EntityStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityStart.Unmarshal(m, b)
}
func (m *EntityStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityStart.Marshal(b, m, deterministic)
}
func (m *EntityStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityStart.Merge(m, src)
}
func (m *EntityStart) XXX_Size() int {
	return xxx_messageInfo_EntityStart.Size(m)
}
func (m *EntityStart) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityStart.DiscardUnknown(m)
}

var xxx_messageInfo_EntityStart proto.InternalMessageInfo

func (m *EntityStart) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *EntityStart) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

func (m *EntityStart) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_TEST
}

func (m *EntityStart) GetOutDir() string {
	if m != nil {
		return m.OutDir
	}
	return ""
}

// EntityLog message indicates that an informational log message was produced
// by an entity.
type EntityLog struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	EntityName           string               `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	Text                 string               `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EntityLog) Reset()         { *m = EntityLog{} }
func (m *EntityLog) String() string { return proto.CompactTextString(m) }
func (*EntityLog) ProtoMessage()    {}
func (*EntityLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{4}
}

func (m *EntityLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityLog.Unmarshal(m, b)
}
func (m *EntityLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityLog.Marshal(b, m, deterministic)
}
func (m *EntityLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityLog.Merge(m, src)
}
func (m *EntityLog) XXX_Size() int {
	return xxx_messageInfo_EntityLog.Size(m)
}
func (m *EntityLog) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityLog.DiscardUnknown(m)
}

var xxx_messageInfo_EntityLog proto.InternalMessageInfo

func (m *EntityLog) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *EntityLog) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

func (m *EntityLog) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// EntityError indicates that an error was produced by an entity. A consumer
// should treat an entity as failed when it sees one or more errors reported for
// it.
type EntityError struct {
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	EntityName           string               `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	ErrorDetails         *ErrorDetails        `protobuf:"bytes,3,opt,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EntityError) Reset()         { *m = EntityError{} }
func (m *EntityError) String() string { return proto.CompactTextString(m) }
func (*EntityError) ProtoMessage()    {}
func (*EntityError) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{5}
}

func (m *EntityError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityError.Unmarshal(m, b)
}
func (m *EntityError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityError.Marshal(b, m, deterministic)
}
func (m *EntityError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityError.Merge(m, src)
}
func (m *EntityError) XXX_Size() int {
	return xxx_messageInfo_EntityError.Size(m)
}
func (m *EntityError) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityError.DiscardUnknown(m)
}

var xxx_messageInfo_EntityError proto.InternalMessageInfo

func (m *EntityError) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *EntityError) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

func (m *EntityError) GetErrorDetails() *ErrorDetails {
	if m != nil {
		return m.ErrorDetails
	}
	return nil
}

// ErrorDetails describes details of an error reported by an entity.
type ErrorDetails struct {
	Reason               string         `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Location             *ErrorLocation `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ErrorDetails) Reset()         { *m = ErrorDetails{} }
func (m *ErrorDetails) String() string { return proto.CompactTextString(m) }
func (*ErrorDetails) ProtoMessage()    {}
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{6}
}

func (m *ErrorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDetails.Unmarshal(m, b)
}
func (m *ErrorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDetails.Marshal(b, m, deterministic)
}
func (m *ErrorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDetails.Merge(m, src)
}
func (m *ErrorDetails) XXX_Size() int {
	return xxx_messageInfo_ErrorDetails.Size(m)
}
func (m *ErrorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDetails proto.InternalMessageInfo

func (m *ErrorDetails) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ErrorDetails) GetLocation() *ErrorLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

// ErrorLocation represents a code location where an error was reported.
type ErrorLocation struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line                 int64    `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Stack                string   `protobuf:"bytes,3,opt,name=stack,proto3" json:"stack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorLocation) Reset()         { *m = ErrorLocation{} }
func (m *ErrorLocation) String() string { return proto.CompactTextString(m) }
func (*ErrorLocation) ProtoMessage()    {}
func (*ErrorLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{7}
}

func (m *ErrorLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorLocation.Unmarshal(m, b)
}
func (m *ErrorLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorLocation.Marshal(b, m, deterministic)
}
func (m *ErrorLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorLocation.Merge(m, src)
}
func (m *ErrorLocation) XXX_Size() int {
	return xxx_messageInfo_ErrorLocation.Size(m)
}
func (m *ErrorLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorLocation.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorLocation proto.InternalMessageInfo

func (m *ErrorLocation) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ErrorLocation) GetLine() int64 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *ErrorLocation) GetStack() string {
	if m != nil {
		return m.Stack
	}
	return ""
}

// EntityEnd message marks the end of an entity run.
type EntityEnd struct {
	Time       *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	EntityName string               `protobuf:"bytes,2,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*EntityEnd_Finished
	//	*EntityEnd_Skipped
	Result               isEntityEnd_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *EntityEnd) Reset()         { *m = EntityEnd{} }
func (m *EntityEnd) String() string { return proto.CompactTextString(m) }
func (*EntityEnd) ProtoMessage()    {}
func (*EntityEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{8}
}

func (m *EntityEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityEnd.Unmarshal(m, b)
}
func (m *EntityEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityEnd.Marshal(b, m, deterministic)
}
func (m *EntityEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityEnd.Merge(m, src)
}
func (m *EntityEnd) XXX_Size() int {
	return xxx_messageInfo_EntityEnd.Size(m)
}
func (m *EntityEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityEnd.DiscardUnknown(m)
}

var xxx_messageInfo_EntityEnd proto.InternalMessageInfo

func (m *EntityEnd) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *EntityEnd) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

type isEntityEnd_Result interface {
	isEntityEnd_Result()
}

type EntityEnd_Finished struct {
	Finished *EntityFinished `protobuf:"bytes,3,opt,name=finished,proto3,oneof"`
}

type EntityEnd_Skipped struct {
	Skipped *EntitySkipped `protobuf:"bytes,4,opt,name=skipped,proto3,oneof"`
}

func (*EntityEnd_Finished) isEntityEnd_Result() {}

func (*EntityEnd_Skipped) isEntityEnd_Result() {}

func (m *EntityEnd) GetResult() isEntityEnd_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *EntityEnd) GetFinished() *EntityFinished {
	if x, ok := m.GetResult().(*EntityEnd_Finished); ok {
		return x.Finished
	}
	return nil
}

func (m *EntityEnd) GetSkipped() *EntitySkipped {
	if x, ok := m.GetResult().(*EntityEnd_Skipped); ok {
		return x.Skipped
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EntityEnd) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EntityEnd_Finished)(nil),
		(*EntityEnd_Skipped)(nil),
	}
}

// EntityFinished indicates that an entity was finished. A finished entity is
// considered failed if one or more errors were reported; otherwise it is
// considered passed.
type EntityFinished struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityFinished) Reset()         { *m = EntityFinished{} }
func (m *EntityFinished) String() string { return proto.CompactTextString(m) }
func (*EntityFinished) ProtoMessage()    {}
func (*EntityFinished) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{9}
}

func (m *EntityFinished) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityFinished.Unmarshal(m, b)
}
func (m *EntityFinished) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityFinished.Marshal(b, m, deterministic)
}
func (m *EntityFinished) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityFinished.Merge(m, src)
}
func (m *EntityFinished) XXX_Size() int {
	return xxx_messageInfo_EntityFinished.Size(m)
}
func (m *EntityFinished) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityFinished.DiscardUnknown(m)
}

var xxx_messageInfo_EntityFinished proto.InternalMessageInfo

// EntitySkipped indicates that an entity was skipped. No errors should be
// reported for a skipped tests though informational logs might be emitted.
type EntitySkipped struct {
	Reasons              []string `protobuf:"bytes,1,rep,name=reasons,proto3" json:"reasons,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntitySkipped) Reset()         { *m = EntitySkipped{} }
func (m *EntitySkipped) String() string { return proto.CompactTextString(m) }
func (*EntitySkipped) ProtoMessage()    {}
func (*EntitySkipped) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a0b3d6cfd712914, []int{10}
}

func (m *EntitySkipped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntitySkipped.Unmarshal(m, b)
}
func (m *EntitySkipped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntitySkipped.Marshal(b, m, deterministic)
}
func (m *EntitySkipped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntitySkipped.Merge(m, src)
}
func (m *EntitySkipped) XXX_Size() int {
	return xxx_messageInfo_EntitySkipped.Size(m)
}
func (m *EntitySkipped) XXX_DiscardUnknown() {
	xxx_messageInfo_EntitySkipped.DiscardUnknown(m)
}

var xxx_messageInfo_EntitySkipped proto.InternalMessageInfo

func (m *EntitySkipped) GetReasons() []string {
	if m != nil {
		return m.Reasons
	}
	return nil
}

func init() {
	proto.RegisterEnum("tast.core.EntityType", EntityType_name, EntityType_value)
	proto.RegisterType((*ControlMessage)(nil), "tast.core.ControlMessage")
	proto.RegisterType((*RunStart)(nil), "tast.core.RunStart")
	proto.RegisterType((*RunLog)(nil), "tast.core.RunLog")
	proto.RegisterType((*EntityStart)(nil), "tast.core.EntityStart")
	proto.RegisterType((*EntityLog)(nil), "tast.core.EntityLog")
	proto.RegisterType((*EntityError)(nil), "tast.core.EntityError")
	proto.RegisterType((*ErrorDetails)(nil), "tast.core.ErrorDetails")
	proto.RegisterType((*ErrorLocation)(nil), "tast.core.ErrorLocation")
	proto.RegisterType((*EntityEnd)(nil), "tast.core.EntityEnd")
	proto.RegisterType((*EntityFinished)(nil), "tast.core.EntityFinished")
	proto.RegisterType((*EntitySkipped)(nil), "tast.core.EntitySkipped")
}

func init() { proto.RegisterFile("testing.proto", fileDescriptor_7a0b3d6cfd712914) }

var fileDescriptor_7a0b3d6cfd712914 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdf, 0x4e, 0xdb, 0x3e,
	0x18, 0x6d, 0x69, 0x69, 0x9b, 0xaf, 0x14, 0xf1, 0xf3, 0x8f, 0x41, 0x86, 0x34, 0xc1, 0xc2, 0x0d,
	0x4c, 0x53, 0x2a, 0x31, 0xb6, 0x5d, 0x6c, 0x57, 0x8c, 0x20, 0x26, 0xc1, 0x2e, 0x4c, 0x27, 0x4d,
	0xd3, 0xa4, 0x2a, 0x34, 0xa6, 0x58, 0x24, 0x76, 0x64, 0x3b, 0xd2, 0x78, 0x97, 0xbd, 0xc3, 0x9e,
	0x66, 0x8f, 0xb0, 0xf7, 0x98, 0xfc, 0xaf, 0x4d, 0x57, 0x71, 0x31, 0x89, 0xbb, 0xef, 0xcb, 0xf9,
	0x8e, 0x8f, 0x73, 0x8e, 0x6d, 0x18, 0x28, 0x22, 0x15, 0x65, 0xd3, 0xb8, 0x14, 0x5c, 0x71, 0x14,
	0xa8, 0x54, 0xaa, 0x78, 0xc2, 0x05, 0xd9, 0xd9, 0x9d, 0x72, 0x3e, 0xcd, 0xc9, 0xd0, 0x00, 0xd7,
	0xd5, 0xcd, 0x50, 0xd1, 0x82, 0x48, 0x95, 0x16, 0xa5, 0x9d, 0x8d, 0x7e, 0xaf, 0xc0, 0xfa, 0x07,
	0xce, 0x94, 0xe0, 0xf9, 0x25, 0x91, 0x32, 0x9d, 0x12, 0x74, 0x04, 0x81, 0xa8, 0xd8, 0x58, 0xaa,
	0x54, 0xa8, 0xb0, 0xb9, 0xd7, 0x3c, 0xe8, 0x1f, 0xfd, 0x1f, 0xcf, 0x96, 0x8c, 0x71, 0xc5, 0xae,
	0x34, 0x74, 0xde, 0xc0, 0x3d, 0xe1, 0x6a, 0xf4, 0x12, 0xba, 0x9a, 0x93, 0xf3, 0x69, 0xb8, 0x62,
	0x18, 0xff, 0x2d, 0x32, 0x2e, 0xf8, 0xf4, 0xbc, 0x81, 0x3b, 0xc2, 0x54, 0xe8, 0x1d, 0xac, 0x11,
	0xa6, 0xa8, 0xba, 0x77, 0x22, 0x2d, 0x43, 0xd9, 0xaa, 0x51, 0x12, 0x03, 0x7b, 0x9d, 0x3e, 0x99,
	0xb7, 0xe8, 0x35, 0x80, 0x23, 0x6b, 0xb5, 0xb6, 0xa1, 0x6e, 0x2e, 0x51, 0xad, 0x60, 0x40, 0x7c,
	0x53, 0xd3, 0x24, 0x42, 0x70, 0x11, 0xae, 0x3e, 0xa0, 0x99, 0x68, 0x74, 0xae, 0x69, 0xda, 0x9a,
	0x26, 0x61, 0x59, 0xd8, 0x79, 0x40, 0x33, 0x61, 0xd9, 0x5c, 0x33, 0x61, 0xd9, 0x49, 0x00, 0xdd,
	0xc2, 0x9a, 0x1a, 0x1d, 0x42, 0xcf, 0x1b, 0x87, 0x9e, 0x01, 0xe8, 0xc0, 0xc6, 0x2c, 0x2d, 0x88,
	0x0c, 0x9b, 0x7b, 0xad, 0x83, 0x00, 0x07, 0xfa, 0xcb, 0x27, 0xfd, 0x21, 0xba, 0x80, 0x8e, 0x75,
	0x0c, 0xc5, 0xd0, 0xd6, 0x79, 0xb9, 0x10, 0x76, 0x62, 0x1b, 0x66, 0xec, 0xc3, 0x8c, 0x47, 0x3e,
	0x4c, 0x6c, 0xe6, 0x10, 0x82, 0xb6, 0x22, 0xdf, 0x95, 0x89, 0x20, 0xc0, 0xa6, 0x8e, 0x7e, 0x36,
	0xa1, 0x5f, 0x73, 0xf3, 0x9f, 0xd7, 0xdc, 0x05, 0xe7, 0x84, 0xd9, 0xae, 0x5b, 0xda, 0xb9, 0xa1,
	0xf7, 0x8b, 0xde, 0xcc, 0x06, 0xd4, 0x7d, 0x49, 0x4c, 0x96, 0xeb, 0x47, 0x4f, 0x96, 0xcc, 0x19,
	0xdd, 0x97, 0xc4, 0xf3, 0x74, 0x8d, 0xb6, 0xa1, 0xcb, 0x2b, 0x35, 0xce, 0xa8, 0x30, 0x21, 0x06,
	0xb8, 0xc3, 0x2b, 0x75, 0x4a, 0x45, 0x54, 0x42, 0x30, 0xcb, 0xf0, 0xf1, 0xb7, 0xeb, 0x3d, 0x6a,
	0xd5, 0x3c, 0xfa, 0x31, 0xf3, 0xc8, 0xc6, 0xfd, 0xe8, 0xa2, 0xef, 0x61, 0x60, 0x4e, 0xdd, 0x38,
	0x23, 0x2a, 0xa5, 0xb9, 0x74, 0x27, 0x7e, 0xbb, 0xee, 0x92, 0xc6, 0x4f, 0x2d, 0x8c, 0xd7, 0x48,
	0xad, 0x8b, 0xbe, 0xc1, 0x5a, 0x1d, 0x45, 0x5b, 0xd0, 0x11, 0x24, 0x95, 0x9c, 0x99, 0x0d, 0x06,
	0xd8, 0x75, 0xe8, 0x18, 0x7a, 0x39, 0x9f, 0xa4, 0x8a, 0x72, 0xe6, 0x6e, 0x61, 0xf8, 0xb7, 0xc0,
	0x85, 0xc3, 0xf1, 0x6c, 0x32, 0xba, 0x84, 0xc1, 0x02, 0xa4, 0x1d, 0xba, 0xa1, 0x39, 0x71, 0x8b,
	0x9b, 0x5a, 0x7f, 0xcb, 0x29, 0xb3, 0xbf, 0xd6, 0xc2, 0xa6, 0x46, 0x9b, 0xb0, 0x2a, 0x55, 0x3a,
	0xb9, 0x73, 0x56, 0xda, 0x26, 0xfa, 0xd5, 0xf4, 0xf1, 0x25, 0x2c, 0x7b, 0x7c, 0x27, 0xdf, 0x42,
	0xef, 0x86, 0x32, 0x2a, 0x6f, 0x49, 0xe6, 0x4c, 0x7c, 0xba, 0x74, 0xd4, 0xce, 0xdc, 0x80, 0x7e,
	0xa1, 0xfc, 0x30, 0x3a, 0x86, 0xae, 0xbc, 0xa3, 0x65, 0x49, 0x32, 0xf7, 0x66, 0x84, 0xcb, 0xcf,
	0x8d, 0xc5, 0xcf, 0x1b, 0xd8, 0x8f, 0x9e, 0xf4, 0xb4, 0xd5, 0xb2, 0xca, 0x55, 0xb4, 0x01, 0xeb,
	0x8b, 0xab, 0x47, 0x87, 0x30, 0x58, 0xe0, 0xa1, 0x10, 0xba, 0x36, 0x09, 0x7f, 0xa9, 0x7d, 0xfb,
	0x62, 0x1f, 0x60, 0x7e, 0x0b, 0x50, 0x0f, 0xda, 0xa3, 0xe4, 0x6a, 0xb4, 0xd1, 0x40, 0x7d, 0xe8,
	0x9e, 0x7d, 0xfc, 0x32, 0xfa, 0x8c, 0x93, 0x8d, 0xe6, 0xc9, 0xfe, 0xd7, 0xe7, 0x93, 0x5b, 0xc1,
	0x0b, 0x5a, 0x15, 0x5c, 0x0e, 0xf5, 0xe6, 0x86, 0x94, 0x29, 0x22, 0x58, 0x9a, 0xdb, 0xf7, 0x7b,
	0xc2, 0xf3, 0xeb, 0x8e, 0xa9, 0x5e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xa4, 0xb2, 0x83,
	0xf3, 0x05, 0x00, 0x00,
}
